'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const cohort='/home/spark-advantage/rek-training/timing500-ppo-live-20260924-r1';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
assert(!fs.existsSync('/proc/2962307'),'cohort controller still present');
const ledgerBytes=fs.readFileSync(cohort+'/root-campaign/ledger.json');
const logBytes=fs.readFileSync(cohort+'/root-campaign/campaign.log');
const events=logBytes.toString().trim().split(/\r?\n/).map(JSON.parse);
assert.equal(events.at(-1).event,'campaign_end');
assert.equal(events.at(-1).utc,'2026-09-24T11:00:34.706Z');
assert(events.some(e=>e.event==='criterion_failed'&&e.counted===5&&e.nonwins===3));
const all=Object.values(JSON.parse(ledgerBytes)).flat();
const complete=all.filter(e=>e.complete);
assert.equal(complete.length,5);assert.equal(all.length-complete.length,9);
const selection=JSON.parse(fs.readFileSync(path.join(__dirname,'selection.example.json')));
selection.minimum_completed_rounds=5;
selection.minimum_override_reason='All five completed C2 behavior rounds from the closed cohort, including both wins and all three losses; explicit development-training minimum5 after failure of the18/20 criterion. No losses discarded.';
selection.cohort={path:cohort,ended_utc:events.at(-1).utc,ledger_sha256:hash(ledgerBytes),log_sha256:hash(logBytes),wins:2,losses:3,points:[49,55],incomplete_attempts:9};
selection.rounds=complete.map(e=>{
  assert(e.terminal&&e.same_bot&&e.fair_start&&e.wrapper_exit===0);
  const config=JSON.parse(fs.readFileSync(e.config));
  assert.equal(config.checkpoint_sha256,selection.checkpoint.sha256);
  const seed=Number(config.worker[3]);assert(Number.isSafeInteger(seed));
  return {id:path.basename(e.dir),seed,directory:e.dir,config:e.config};
});
assert.deepEqual(selection.rounds.map(r=>r.seed),[1301,1302,1303,1304,1305]);
const scores=complete.map(e=>e.final_round.clean_hits);
assert.deepEqual(scores,[[2,6],[9,11],[20,14],[12,10],[6,14]]);
require('./selection.cjs').validateSelection(selection);
require('./selection.cjs').loadNativeSelection(selection);
const output=path.join(__dirname,'selection.json');
fs.writeFileSync(output,JSON.stringify(selection,null,2)+'\n',{flag:'wx',mode:0o600});
console.log(JSON.stringify({path:output,sha256:hash(fs.readFileSync(output)),rounds:selection.rounds.length,cohort:selection.cohort}));
