#!/usr/bin/env python3
"""Closed-loop check of the lite falls pipeline.

Data generated by the lite runtime under a KNOWN model (the synthetic smoke
model), aggregated by the dataset logger's own code and fitted by
fit_lite_falls.py, must give back that model's behavior on held-out data:

  * held-out log loss within 2% of the true model's (it cannot honestly beat it
    by much, and must not be much worse);
  * held-out expected onsets within 10% of observed;
  * the high-risk cells (kicks at close range) and idle cells within a factor
    of two of the true hazard;
  * outcome probabilities and delay medians close to the true ones.

usage: check_lite_fall_recovery.py TRUE_MODEL FITTED_MODEL HOLDOUT_DATASET
"""
import json
import sys

import numpy as np

import fit_lite_falls as lf


def load(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def weights(model):
    w = np.zeros(lf.PARAMETERS)
    o = lf.OFFSETS
    w[o["bias"][0]] = model["bias"]
    w[o["own"][0]:o["own"][0] + lf.MOVE_BINS] = model["own_move"]
    w[o["opponent"][0]:o["opponent"][0] + lf.MOVE_BINS] = model["opponent_move"]
    w[o["distance"][0]:o["distance"][0] + lf.DISTANCE_BINS] = model["distance"]
    w[o["closing"][0]:o["closing"][0] + lf.CLOSING_BINS] = model["closing"]
    w[o["own_distance"][0]:o["own_distance"][0] + lf.MOVE_BINS * lf.DISTANCE_BINS] = np.ravel(model["own_move_distance"])
    w[o["opponent_distance"][0]:o["opponent_distance"][0] + lf.MOVE_BINS * lf.DISTANCE_BINS] = np.ravel(model["opponent_move_distance"])
    w[o["struck"][0]] = model["struck"]
    return w


def main():
    true_model, fitted_model, holdout = load(sys.argv[1]), load(sys.argv[2]), lf.load_dataset(sys.argv[3])
    failures = []

    def check(ok, message):
        print(("PASS " if ok else "FAIL ") + message)
        if not ok:
            failures.append(message)

    truth, fitted = lf.evaluate(weights(true_model), holdout), lf.evaluate(weights(fitted_model), holdout)
    print(json.dumps({"holdout_onsets": truth["onsets"], "true_log_loss": truth["log_loss_per_tick"],
                      "fitted_log_loss": fitted["log_loss_per_tick"],
                      "constant_rate_log_loss": truth["constant_rate_log_loss_per_tick"],
                      "fitted_expected_onsets": fitted["expected_onsets"]}))
    check(holdout["_onsets"].sum() >= 500, "holdout has at least 500 onsets")
    check(fitted["log_loss_per_tick"] <= 1.02 * truth["log_loss_per_tick"], "fitted held-out log loss within 2% of the true model")
    check(fitted["log_loss_per_tick"] < 0.9 * truth["constant_rate_log_loss_per_tick"], "fitted model beats a constant rate")
    check(abs(fitted["expected_onsets"] - fitted["onsets"]) <= 0.1 * fitted["onsets"], "held-out onsets calibrated within 10%")

    def hazard(model, own, opp=lf.IDLE_BIN, distance=0, closing=1, struck=0):
        w = weights(model)
        columns, struck_values = lf.design(np.array([own]), np.array([opp]), np.array([distance]),
                                           np.array([closing]), np.array([struck]))
        return float(1 / (1 + np.exp(-lf.logits(w, columns, struck_values)[0])))

    exposures = holdout["_exposures"].reshape(lf.CELL_SHAPE)
    hh_mid = 7 * lf.PHASE_BINS + 1
    for name, own, distance in (("HH mid-phase at close range", hh_mid, 0),
                                ("HH mid-phase at 0.55-0.85 m", hh_mid, 1)):
        support = exposures[own, :, distance].sum()
        t, f = hazard(true_model, own, distance=distance), hazard(fitted_model, own, distance=distance)
        print(json.dumps({"cell": name, "exposure_ticks": int(support), "true_hazard": t, "fitted_hazard": f}))
        if support >= 2000:
            check(0.5 <= f / t <= 2.0, f"{name}: fitted hazard within 2x of truth")
    t, f = hazard(true_model, lf.IDLE_BIN, distance=4), hazard(fitted_model, lf.IDLE_BIN, distance=4)
    print(json.dumps({"cell": "idle far", "true_hazard": t, "fitted_hazard": f}))
    check(f <= 20 * t, "idle hazard stays near the tiny true value")

    true_p, fitted_p = np.array(true_model["outcome_probability"]), np.array(fitted_model["outcome_probability"])
    counts = np.array(holdout["outcomes"]["counts_by_class"]).sum(axis=1)
    for c in range(lf.CLASSES):
        print(json.dumps({"class": c, "outcomes": int(counts[c]), "true": true_p[c].tolist(), "fitted": fitted_p[c].tolist()}))
    kick = 2
    check(np.max(np.abs(true_p[kick] - fitted_p[kick])) <= 0.08, "kick-class outcome probabilities within 0.08")
    for o, name in enumerate(("recover", "fallen_quick", "stuck")):
        t_median = true_model["delay_quantiles_ticks"][o][4]
        f_median = fitted_model["delay_quantiles_ticks"][o][4]
        print(json.dumps({"delay": name, "true_median_ticks": t_median, "fitted_median_ticks": f_median}))
        check(abs(f_median - t_median) <= max(5.0, 0.25 * t_median), f"{name} delay median within 25%")
    print(("FAIL" if failures else "PASS") + f": {len(failures)} failures")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
