// Move table for the REK G1 combat env.
//
// REK's G1s do not accept joint-level commands: the pilot presses a key and the
// robot executes a *set move*, with REK's own self-balancing controller running
// the joints underneath. So a move here is a fighting-game frame envelope
// (startup / active / recovery) plus the hit volume it sweeps, not a trajectory.
//
// The table below is a placeholder roster calibrated to published Unitree G1
// reach/mass numbers. tools/extract_rek.py dumps the real roster out of REK's
// Unity assets and writes moves_generated.h; when that file is present it wins.
// Everything downstream (action-head width, obs layout) is derived from
// NUM_MOVE_DEFS, so swapping the table needs no other code change.

#pragma once

#include <stdbool.h>

// Sim runs at 30 Hz. All frame counts below are in 30 Hz frames.
#define REK_TICK_HZ 30.0f
#define REK_DT (1.0f / REK_TICK_HZ)

typedef struct {
    const char* name;
    int startup;          // frames before the hit volume goes live
    int active;           // frames the hit volume is live
    int recovery;         // frames after the active window, still committed
    float reach;          // hit volume centre, metres forward of the root
    float radius;         // hit volume radius, metres
    float damage;         // scoreboard value of a clean hit (REK counts hits)
    float balance_cost;   // balance the attacker spends throwing it
    float balance_impact; // balance inflicted on a clean hit
    float root_motion;    // metres travelled forward over the whole move
    bool guard_breaks;    // lands full impact even against a raised guard
} MoveDef;

// Index 0 is the neutral "no move" entry and is never executed. Keeping it in
// the table means move id and action index are the same number everywhere.
static const MoveDef REK_MOVES[] = {
    // name        start act  rec  reach  rad   dmg  bcost bimp  root   gbreak
    {"neutral",        0,  0,   0, 0.00f, 0.00f, 0.0f, 0.00f, 0.00f, 0.00f, false},
    {"jab",            2,  2,   4, 0.62f, 0.20f, 1.0f, 0.02f, 0.10f, 0.06f, false},
    {"cross",          4,  2,   7, 0.70f, 0.22f, 1.0f, 0.05f, 0.20f, 0.12f, false},
    {"hook",           6,  3,   9, 0.58f, 0.26f, 1.0f, 0.09f, 0.30f, 0.10f, false},
    {"uppercut",       7,  3,  11, 0.48f, 0.24f, 1.0f, 0.12f, 0.38f, 0.08f, false},
    {"front_kick",     8,  3,  12, 0.95f, 0.26f, 1.0f, 0.15f, 0.34f, 0.18f, false},
    {"roundhouse",    11,  4,  16, 1.05f, 0.30f, 1.0f, 0.22f, 0.52f, 0.14f, false},
    {"shove",          5,  3,   8, 0.55f, 0.32f, 0.0f, 0.08f, 0.45f, 0.22f, true },
};

#if defined(__has_include)
#if __has_include("moves_generated.h")
// Generated by tools/extract_rek.py from the shipped Unity assets. Defines
// REK_MOVES_GENERATED[] and REK_NUM_MOVES_GENERATED.
#include "moves_generated.h"
#define REK_USING_GENERATED_MOVES 1
#endif
#endif

#ifdef REK_USING_GENERATED_MOVES
#define REK_MOVE_TABLE REK_MOVES_GENERATED
#define NUM_MOVE_DEFS REK_NUM_MOVES_GENERATED
#else
#define REK_MOVE_TABLE REK_MOVES
#define NUM_MOVE_DEFS ((int)(sizeof(REK_MOVES) / sizeof(REK_MOVES[0])))
#endif

// Longest committed window in the table, used to normalise the frame counter
// into the observation without a per-step search.
static inline int rek_move_total(int move_id) {
    const MoveDef* m = &REK_MOVE_TABLE[move_id];
    return m->startup + m->active + m->recovery;
}
