#!/usr/bin/env python3
"""Run the fail-closed six-command REK motion-parity evidence suite.

The suite consumes completed protocol-v6 recorder runs, their semantic bridge
transcripts, sealed frame captures, explicit measured coordinate calibrations,
and one independently measured simulator trace/capture per command.  It does
not collect live input, infer a coordinate transform, choose a clock offset, or
invent an error allowance.

Every command is first imported and compared without video.  A paired MP4 is
rendered only if the existing comparator returns a measured passing verdict.
Both video anchors are then regenerated by ``video_clock_anchor.py`` from exact
rendered-marker transitions in sealed frame captures.  Supplied/manual clock
offsets and pre-written anchor sidecars are deliberately unsupported.

This program covers the six velocity commands currently exported by
``ocean/rek_fight/export_motion_trace.py``.  It makes no combat-move or complete
REK-moveset claim.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence


SUITE_SCHEMA = "rek.motion_parity_suite.v1"
TRACE_SCHEMA = "rek.paired_motion_trace.v1"
CALIBRATION_SCHEMA = "rek.paired_motion_calibration.v1"
COMPARISON_SCHEMA = "rek.paired_motion_comparison.v1"
ANCHOR_SCHEMA = "rek.video_clock_anchor.v1"
CAPTURE_SCHEMA = "rek.spark_x11_frame_capture.v2"
SIM_CAPTURE_SCHEMA = "rek.simulator_frame_capture.v1"
MEASURED_ANCHOR_METHOD = "rendered_command_marker_transition_v1"
MEASURED_MARKER_TRANSITION = "persistent_exact_rgb_rising_edge"
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
ENGINEAI_SDK_COMMIT = "335c60e88772c26c7852d0abd6b3c7439037dd8f"
WALKING_POLICY_SHA256 = (
    "cbcb90f86dbb2fde39bdc5a25c8d0530d5c79c7a8f84b1f90863d8c9065b6427"
)
RECOVERY_POLICY_SHA256 = (
    "deb9974b1f4f4a7e77801f8c9c6e77f599caab0ca4dd7709fe0bae55870e0e86"
)
RECOVERY_TRAJECTORY_SHA256 = (
    "c2f19c164093701311634024eb27999fed4631a00d38d507f8aa306ee138c161"
)
TRIAL_SCHEMA = "rek.clone.single_press_trial.v1"
RESET_SCHEMA = "rek.clone.composite_reset.v1"
TRIAL_PROTOCOL_ID = "rek.clone.isolated_same_reset_single_press.50hz.v1"
TRIAL_RATE_HZ = 50.0
TRIAL_FIXED_SUBSTEPS = 10
TRIAL_NEUTRAL_START_TICK = 0
TRIAL_PRESS_TICK = 50
TRIAL_RELEASE_TICK = 150
TRIAL_STOP_TICK = 200
RESET_KEYFRAME_ID = 0
RESET_KEYFRAME_NAME = "client_observed_round2_first_active"
EXPECTED_KEYFRAME_QPOS_SHA256 = (
    "442174dccf2137fbb53a02b8bbf2b7ae566c777a88fbd9e62b056e899d616910"
)
EXPECTED_COMPOSITE_RESET_QPOS_SHA256 = (
    "98ec4bdd0e7f7943442e2a64ec55d3b0c204aa8106a724cc7e619280e84edc92"
)
EXPECTED_CANONICAL_STATE_AUTHORITY = {
    "kind": "engineai_native_sdk_model_and_walking_configuration",
    "sdk_commit": ENGINEAI_SDK_COMMIT,
    "model_path": "assets/resource/t800.xml",
    "walking_configuration_path": (
        "assets/config/t800/rl_walking_example/default.yaml"
    ),
    "default_joint_q_sha256": (
        "da20862b7f3cc8252146e11ed3f534711898a012f698cb44ffd792199f6b26cd"
    ),
    "root_clearance_above_support_m": 1.03,
    "root_orientation": "sdk_upright_roll_pitch_with_retained_arena_heading",
    "root_and_joint_velocities": "zero",
    "support_geometry": "arena_Collider_Floor_Rektagon",
    "support_height_m": 0.009999997913837433,
}
NEUTRAL_COMMAND = (0.0, 0.0, 0.0)
TRIAL_PROTOCOL_DEFINITION = {
    "schema": TRIAL_SCHEMA,
    "identity": TRIAL_PROTOCOL_ID,
    "trial_rate_hz": TRIAL_RATE_HZ,
    "neutral_start_trial_tick": TRIAL_NEUTRAL_START_TICK,
    "press_trial_tick": TRIAL_PRESS_TICK,
    "release_trial_tick": TRIAL_RELEASE_TICK,
    "stop_trial_tick": TRIAL_STOP_TICK,
    "controlled_fighter_initialization": "same_composite_reset_for_every_selector",
    "controlled_fighter_command_contract": (
        "neutral_pre_roll_then_one_non_neutral_press_then_neutral_release"
    ),
    "attack_command_count": 0,
}


@dataclass(frozen=True)
class MotionSpec:
    selector: str
    command_identity: str
    simulator_command: str
    normalized_command: tuple[float, float, float]
    rek_edge_schedule_tick: int
    rek_release_schedule_tick: int

    @property
    def slug(self) -> str:
        return self.selector.replace(".", "_").replace(":", "_")


# The list is intentionally explicit.  Repeated schedule occurrences and
# release edges are not silently substituted for these six single-command
# executions.  Attacks are not listed because the current simulator exporter
# explicitly does not produce combat trajectories.
MOTIONS = (
    MotionSpec(
        "walk_forward.press.1", "walk_forward:press:v1", "forward",
        (1.0, 0.0, 0.0), 50, 150,
    ),
    MotionSpec(
        "walk_backward.press.1", "walk_backward:press:v1", "backward",
        (-1.0, 0.0, 0.0), 200, 300,
    ),
    MotionSpec(
        "strafe_left.press.1", "strafe_left:press:v1", "strafe-left",
        (0.0, -1.0, 0.0), 350, 450,
    ),
    MotionSpec(
        "strafe_right.press.1", "strafe_right:press:v1", "strafe-right",
        (0.0, 1.0, 0.0), 500, 600,
    ),
    MotionSpec(
        "yaw_left.press.1", "yaw_left:press:v1", "yaw-left",
        (0.0, 0.0, -1.0), 650, 750,
    ),
    MotionSpec(
        "yaw_right.press.1", "yaw_right:press:v1", "yaw-right",
        (0.0, 0.0, 1.0), 800, 900,
    ),
)
MOTION_SELECTORS = tuple(motion.selector for motion in MOTIONS)


class SuiteError(RuntimeError):
    """Inputs or tool output cannot support the requested suite."""


@dataclass(frozen=True)
class RekRun:
    raw_trace: Path
    bridge_transcript: Path


@dataclass(frozen=True)
class SuiteConfig:
    rek_runs: tuple[RekRun, ...]
    inventory: Path
    schedule_manifest: Path
    rek_calibration: Path
    sim_calibration: Path
    rek_pilot: str
    sim_pilot: str
    rek_captures: dict[str, Path]
    rek_videos: dict[str, Path]
    rek_marker_contracts: dict[str, Path]
    sim_traces: dict[str, Path]
    sim_captures: dict[str, Path]
    sim_videos: dict[str, Path]
    sim_marker_contracts: dict[str, Path]
    output_dir: Path
    accept_at: str
    start_s: float
    end_s: float
    comparison_fps: float
    maximum_timestamp_uncertainty_s: float
    screen_required: bool
    video_fps: float
    video_layout: str


@dataclass(frozen=True)
class ToolResult:
    exit_code: int
    stdout: str
    stderr: str
    record: dict[str, Any]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _file(path: Path, label: str) -> Path:
    candidate = path.expanduser().absolute()
    if candidate.is_symlink():
        raise SuiteError(f"{label} must not be a symlink: {candidate}")
    try:
        resolved = candidate.resolve(strict=True)
    except OSError as exc:
        raise SuiteError(f"{label} is unavailable: {candidate}") from exc
    if not resolved.is_file():
        raise SuiteError(f"{label} is not a regular file: {resolved}")
    return resolved


def _directory(path: Path, label: str) -> Path:
    candidate = path.expanduser().absolute()
    if candidate.is_symlink():
        raise SuiteError(f"{label} must not be a symlink: {candidate}")
    try:
        resolved = candidate.resolve(strict=True)
    except OSError as exc:
        raise SuiteError(f"{label} is unavailable: {candidate}") from exc
    if not resolved.is_dir():
        raise SuiteError(f"{label} is not a directory: {resolved}")
    return resolved


def _identity(path: Path) -> dict[str, Any]:
    return {
        "path": str(path.resolve()),
        "sha256": _sha256(path),
        "bytes": path.stat().st_size,
    }


def _load_object(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SuiteError(f"cannot read {label} JSON {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise SuiteError(f"{label} must be a JSON object")
    return value


def _finite(value: float, label: str, *, positive: bool = False) -> float:
    if isinstance(value, bool) or not math.isfinite(value):
        raise SuiteError(f"{label} must be finite")
    if positive and value <= 0.0:
        raise SuiteError(f"{label} must be positive")
    return float(value)


def _rate_hz(value: Any, label: str) -> float:
    if not isinstance(value, str) or not value:
        raise SuiteError(f"{label} is absent")
    numerator, separator, denominator = value.partition("/")
    try:
        rate = float(numerator) / (float(denominator) if separator else 1.0)
    except (ValueError, ZeroDivisionError) as exc:
        raise SuiteError(f"{label} is invalid") from exc
    return _finite(rate, label, positive=True)


def _artifact_from_provenance(
    calibration_path: Path,
    provenance: dict[str, Any],
    path_key: str,
    sha_key: str,
    label: str,
) -> dict[str, Any]:
    raw_path = provenance.get(path_key)
    raw_sha = provenance.get(sha_key)
    if not isinstance(raw_path, str) or not raw_path.strip():
        raise SuiteError(f"{label} provenance has no {path_key}")
    if not isinstance(raw_sha, str) or not SHA256_PATTERN.fullmatch(raw_sha.lower()):
        raise SuiteError(f"{label} provenance has no valid {sha_key}")
    artifact = Path(raw_path)
    if not artifact.is_absolute():
        artifact = calibration_path.parent / artifact
    artifact = _file(artifact, f"{label} provenance {path_key}")
    observed = _sha256(artifact)
    if observed != raw_sha.lower():
        raise SuiteError(
            f"{label} provenance {path_key} SHA-256 mismatch: "
            f"expected {raw_sha.lower()}, observed {observed}"
        )
    return _identity(artifact)


def validate_shared_calibrations(
    rek_path: Path, sim_path: Path
) -> dict[str, Any]:
    """Prove that two explicit transforms target the same pinned MuJoCo arena.

    The REK transform must bind an observed Unity-to-MuJoCo mapping report.  The
    simulator identity transform must bind both the same report and the MJCF
    named by that report.  No transform is estimated here.
    """
    rek_path = _file(rek_path, "REK calibration")
    sim_path = _file(sim_path, "simulator calibration")
    rek = _load_object(rek_path, "REK calibration")
    sim = _load_object(sim_path, "simulator calibration")
    if rek.get("schema") != CALIBRATION_SCHEMA:
        raise SuiteError("REK calibration has the wrong schema")
    if sim.get("schema") != CALIBRATION_SCHEMA:
        raise SuiteError("simulator calibration has the wrong schema")
    if rek.get("mode") != "explicit_similarity_3d":
        raise SuiteError("REK calibration must be an explicit measured transform")
    if sim.get("mode") not in {"identity", "explicit_similarity_3d"}:
        raise SuiteError("simulator calibration mode is unsupported")
    expected_rek_transform = {
        "position_matrix": [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]],
        "position_offset": [0.0, 0.0, 0.0],
        "source_forward_vector": [1.0, 0.0, 0.0],
        "direct_yaw_sign": -1,
        "direct_yaw_offset_rad": 0.0,
    }
    if any(rek.get(key) != value for key, value in expected_rek_transform.items()):
        raise SuiteError(
            "REK calibration transform does not equal the pinned Unity-to-MuJoCo "
            "axis and quaternion mapping"
        )
    if sim.get("mode") != "identity" or sim.get("source_forward_vector") != [
        1.0,
        0.0,
        0.0,
    ]:
        raise SuiteError("simulator calibration is not the pinned MuJoCo identity")
    rek_provenance = rek.get("provenance")
    sim_provenance = sim.get("provenance")
    if not isinstance(rek_provenance, dict) or not rek_provenance:
        raise SuiteError("REK calibration has no measured provenance object")
    if not isinstance(sim_provenance, dict) or not sim_provenance:
        raise SuiteError("simulator calibration has no measured provenance object")
    if rek_provenance.get("kind") != "pinned_unity_to_mujoco_coordinate_conversion":
        raise SuiteError("REK calibration provenance is not a pinned Unity-to-MuJoCo conversion")
    if sim_provenance.get("kind") != "pinned_mujoco_arena_coordinate_definition":
        raise SuiteError("simulator calibration provenance is not a pinned MuJoCo arena definition")

    rek_report = _artifact_from_provenance(
        rek_path, rek_provenance, "artifact", "artifact_sha256", "REK calibration"
    )
    sim_model = _artifact_from_provenance(
        sim_path, sim_provenance, "artifact", "artifact_sha256", "simulator calibration"
    )
    sim_report = _artifact_from_provenance(
        sim_path,
        sim_provenance,
        "source_report",
        "source_report_sha256",
        "simulator calibration",
    )
    if rek_report["sha256"] != sim_report["sha256"]:
        raise SuiteError(
            "calibrations do not bind the same measured arena mapping report"
        )
    report = _load_object(Path(rek_report["path"]), "shared arena mapping report")
    mapping = report.get("unity_mapping")
    declared_mapping = rek_provenance.get("mapping")
    expected_mapping = {
        "mujoco_position_xyz": ["x", "z", "y"],
        "mujoco_quaternion_wxyz": ["-w", "x", "z", "y"],
    }
    if (
        not isinstance(mapping, dict)
        or not isinstance(declared_mapping, dict)
        or declared_mapping != expected_mapping
        or any(mapping.get(key) != value for key, value in expected_mapping.items())
    ):
        raise SuiteError(
            "REK calibration mapping is not present verbatim in the pinned "
            "report.unity_mapping"
        )
    report_mjcf_sha = report.get("mjcf_sha256")
    if report_mjcf_sha != sim_model["sha256"]:
        raise SuiteError(
            "simulator calibration MJCF does not match the shared report.mjcf_sha256"
        )
    return {
        "state": "measured_shared_target_proven",
        "target_arena_frame": f"mujoco_mjcf_sha256:{sim_model['sha256']}",
        "rek_calibration": _identity(rek_path),
        "sim_calibration": _identity(sim_path),
        "shared_mapping_report": rek_report,
        "simulator_mjcf": sim_model,
        "transform_estimated_by_suite": False,
    }


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")


def _canonical_sha256(value: Any) -> str:
    return hashlib.sha256(_canonical(value)).hexdigest()


def _three_numbers(value: Any, label: str) -> tuple[float, float, float]:
    if not isinstance(value, list) or len(value) != 3:
        raise SuiteError(f"{label} must be a three-number list")
    result = []
    for index, item in enumerate(value):
        if isinstance(item, bool) or not isinstance(item, (int, float)):
            raise SuiteError(f"{label}[{index}] must be a finite number")
        result.append(_finite(float(item), f"{label}[{index}]"))
    return result[0], result[1], result[2]


def _required_sha256(value: Any, label: str) -> str:
    if not isinstance(value, str) or not SHA256_PATTERN.fullmatch(value.lower()):
        raise SuiteError(f"{label} must be a lowercase SHA-256")
    return value.lower()


def _validate_reset_record(
    trace: dict[str, Any], trace_path: Path
) -> dict[str, Any]:
    reset = trace.get("reset")
    if not isinstance(reset, dict) or reset.get("schema") != RESET_SCHEMA:
        raise SuiteError(f"simulator trace {trace_path} has no {RESET_SCHEMA} reset")
    identity_material = reset.get("identity_material")
    measured = reset.get("measured_state")
    if not isinstance(identity_material, dict) or not isinstance(measured, dict):
        raise SuiteError("simulator reset lacks identity material or measured state")
    identity_sha = _required_sha256(
        reset.get("identity_sha256"), "simulator reset identity_sha256"
    )
    if identity_sha != _canonical_sha256(identity_material):
        raise SuiteError("simulator reset identity hash is inconsistent")

    provenance = trace.get("artifact_provenance")
    model = provenance.get("model") if isinstance(provenance, dict) else None
    if not isinstance(model, dict):
        raise SuiteError("simulator reset cannot be bound to a model artifact")
    model_sha = _required_sha256(model.get("sha256"), "simulator model SHA-256")
    expected_identity = {
        "model_sha256": model_sha,
        "keyframe_id": RESET_KEYFRAME_ID,
        "keyframe_name": RESET_KEYFRAME_NAME,
        "keyframe_qpos_sha256_before_joint_override": (
            EXPECTED_KEYFRAME_QPOS_SHA256
        ),
        "composite_qpos_sha256_after_joint_override": (
            EXPECTED_COMPOSITE_RESET_QPOS_SHA256
        ),
        "physics_timestep_s": 1.0 / (TRIAL_RATE_HZ * TRIAL_FIXED_SUBSTEPS),
        "procedure": (
            "mj_resetDataKeyframe_then_retain_arena_xy_heading_and_apply_"
            "per_fighter_engineai_sdk_standing_state_"
            "and_walking_controller_reset_then_mj_forward_v1"
        ),
        "aggregate_state_sha256": measured.get("aggregate_state_sha256"),
        "walking_controller_state_sha256": [
            item.get("state_sha256")
            for item in measured.get("walking_controller_states", [])
            if isinstance(item, dict)
        ],
        "canonical_state_authority": EXPECTED_CANONICAL_STATE_AUTHORITY,
    }
    if identity_material != expected_identity:
        raise SuiteError("simulator reset identity material differs from the pinned reset")
    if measured.get("time_s") != 0.0:
        raise SuiteError("simulator reset measured time is not zero")
    for array_name in ("qpos", "qvel", "act", "ctrl"):
        count = measured.get(f"{array_name}_count")
        if (
            isinstance(count, bool)
            or not isinstance(count, int)
            or count < 0
            or (array_name in {"qpos", "qvel"} and count == 0)
        ):
            raise SuiteError(f"simulator reset has invalid {array_name}_count")
        _required_sha256(
            measured.get(f"{array_name}_sha256"),
            f"simulator reset {array_name}_sha256",
        )
    if measured.get("qpos_sha256") != EXPECTED_COMPOSITE_RESET_QPOS_SHA256:
        raise SuiteError("simulator reset qpos differs from the pinned composite reset")
    _required_sha256(
        measured.get("aggregate_state_sha256"),
        "simulator reset aggregate_state_sha256",
    )
    controller_states = measured.get("walking_controller_states")
    if not isinstance(controller_states, list) or len(controller_states) != 2:
        raise SuiteError("simulator reset lacks both walking-controller states")
    for fighter, state in enumerate(controller_states):
        if not isinstance(state, dict) or state.get("fighter_index") != fighter:
            raise SuiteError("simulator reset walking-controller order is invalid")
        state_material = {key: value for key, value in state.items() if key != "state_sha256"}
        if _required_sha256(
            state.get("state_sha256"),
            f"simulator reset fighter {fighter} controller state SHA-256",
        ) != _canonical_sha256(state_material):
            raise SuiteError("simulator reset controller-state hash is inconsistent")
        _required_sha256(
            state.get("history_sha256"),
            f"simulator reset fighter {fighter} history SHA-256",
        )
        _required_sha256(
            state.get("previous_action_sha256"),
            f"simulator reset fighter {fighter} previous-action SHA-256",
        )
        if (
            state.get("first_observation") is not True
            or state.get("command_filter_output") is not None
        ):
            raise SuiteError("simulator reset controller state is not freshly reset")
    if measured.get("recovering_flags") != [False, False]:
        raise SuiteError("simulator reset recovery flags are not both false")
    expected_steps = [
        {"sequence": 1, "operation": "mj_resetDataKeyframe", "keyframe_id": 0,
         "keyframe_name": RESET_KEYFRAME_NAME},
        {"sequence": 2, "operation": "T800MuJoCoBinding.set_sdk_standing_state",
         "fighter_index": 0, "arena_placement": "retain_keyframe_xy_and_heading",
         "state_authority": "engineai_sdk_model"},
        {"sequence": 3, "operation": "T800WalkingController.reset",
         "fighter_index": 0},
        {"sequence": 4, "operation": "T800MuJoCoBinding.set_sdk_standing_state",
         "fighter_index": 1, "arena_placement": "retain_keyframe_xy_and_heading",
         "state_authority": "engineai_sdk_model"},
        {"sequence": 5, "operation": "T800WalkingController.reset",
         "fighter_index": 1},
        {"sequence": 6, "operation": "set_recovering_flags_false"},
        {"sequence": 7, "operation": "mj_forward"},
        {"sequence": 8, "operation": "set_trial_counters_zero"},
    ]
    if reset.get("procedure_steps") != expected_steps:
        raise SuiteError("simulator reset procedure differs from the pinned procedure")
    if (
        reset.get("untouched_xml_keyframe") is not False
        or reset.get("keyframe_joint_pose_overridden_by_engineai_default_q") is not True
        or reset.get("keyframe_root_state_overridden_by_engineai_sdk_model") is not True
        or reset.get("keyframe_arena_xy_and_heading_retained") is not True
        or reset.get("canonical_state_authority")
        != EXPECTED_CANONICAL_STATE_AUTHORITY
    ):
        raise SuiteError("simulator reset keyframe override declaration is incomplete")
    return {
        "schema": RESET_SCHEMA,
        "identity_sha256": identity_sha,
        "record_sha256": _canonical_sha256(reset),
        "model_sha256": model_sha,
        "aggregate_state_sha256": measured["aggregate_state_sha256"],
    }


def validate_simulator_isolated_trial(
    trace_path: Path,
    motion: MotionSpec,
    start_s: float,
    end_s: float,
) -> dict[str, Any]:
    """Prove one isolated press on a pinned reset and its complete exact grid."""
    trace = _load_object(trace_path, "simulator trace")
    command = trace.get("command")
    trial = trace.get("trial")
    timing = trace.get("timing")
    claims = trace.get("claims")
    if not all(isinstance(item, dict) for item in (command, trial, timing, claims)):
        raise SuiteError("simulator trace lacks command/trial/timing/claim records")
    assert isinstance(command, dict)
    assert isinstance(trial, dict)
    assert isinstance(timing, dict)
    assert isinstance(claims, dict)
    if command.get("identity") != motion.command_identity:
        raise SuiteError("simulator trace has the wrong command identity")
    if command.get("semantic_name") != motion.simulator_command:
        raise SuiteError("simulator trace has the wrong semantic command name")
    if _three_numbers(command.get("normalized_command"), "normalized command") != (
        motion.normalized_command
    ):
        raise SuiteError("simulator trace has the wrong normalized command")
    integer_expectations = {
        "edge_trial_tick": TRIAL_PRESS_TICK,
        "release_trial_tick": TRIAL_RELEASE_TICK,
        "edge_physics_tick": TRIAL_PRESS_TICK * TRIAL_FIXED_SUBSTEPS,
        "release_physics_tick": TRIAL_RELEASE_TICK * TRIAL_FIXED_SUBSTEPS,
        "edge_control_tick": TRIAL_PRESS_TICK * 2,
        "release_control_tick": TRIAL_RELEASE_TICK * 2,
    }
    for key, expected in integer_expectations.items():
        if command.get(key) != expected:
            raise SuiteError(f"simulator command.{key} differs from the isolated trial")
    exact_command_fields = {
        "trial_scope": "isolated_same_reset_single_press",
        "edge_time_s": TRIAL_PRESS_TICK / TRIAL_RATE_HZ,
        "release_time_s": TRIAL_RELEASE_TICK / TRIAL_RATE_HZ,
        "duration_s": (TRIAL_RELEASE_TICK - TRIAL_PRESS_TICK) / TRIAL_RATE_HZ,
    }
    if any(command.get(key) != value for key, value in exact_command_fields.items()):
        raise SuiteError("simulator command timing/scope differs from the isolated trial")
    protocol_sha = _canonical_sha256(TRIAL_PROTOCOL_DEFINITION)
    expected_identity_provenance = {
        "kind": "pinned_isolated_single_press_selector",
        "trial_protocol_identity": TRIAL_PROTOCOL_ID,
        "trial_protocol_sha256": protocol_sha,
    }
    if command.get("identity_provenance") != expected_identity_provenance:
        raise SuiteError("simulator command is not bound to the pinned trial protocol")
    expected_segments = [
        {
            "phase": "neutral_pre_roll",
            "start_trial_tick": TRIAL_NEUTRAL_START_TICK,
            "end_trial_tick_exclusive": TRIAL_PRESS_TICK,
            "normalized_command": list(NEUTRAL_COMMAND),
        },
        {
            "phase": "selected_command_held",
            "start_trial_tick": TRIAL_PRESS_TICK,
            "end_trial_tick_exclusive": TRIAL_RELEASE_TICK,
            "normalized_command": list(motion.normalized_command),
        },
        {
            "phase": "neutral_release",
            "start_trial_tick": TRIAL_RELEASE_TICK,
            "end_trial_tick_exclusive": TRIAL_STOP_TICK,
            "normalized_command": list(NEUTRAL_COMMAND),
        },
    ]
    expected_trial = {
        "schema": TRIAL_SCHEMA,
        "protocol": {
            "identity": TRIAL_PROTOCOL_ID,
            "sha256": protocol_sha,
            "definition": TRIAL_PROTOCOL_DEFINITION,
        },
        "selector": motion.simulator_command,
        "command_identity": motion.command_identity,
        "controlled_command_segments": expected_segments,
        "prior_non_neutral_command_count": 0,
        "non_neutral_press_count": 1,
        "attack_command_count": 0,
    }
    if trial != expected_trial:
        raise SuiteError("simulator trace is not the exact isolated single-press trial")
    expected_claims = {
        "samples_are_measured_simulator_state": True,
        "sample_interpolation_used": False,
        "selected_command_started_from_shared_pinned_reset": True,
        "controlled_prior_non_neutral_command_count": 0,
        "controlled_non_neutral_press_count": 1,
        "controlled_post_release_command_is_neutral": True,
        "rek_attack_trajectories_replayed": False,
    }
    if any(claims.get(key) is not value for key, value in expected_claims.items()):
        raise SuiteError("simulator trace isolated-trial claims are incomplete")
    exact_timing = {
        "physics_dt_s": 0.002,
        "physics_rate_hz": 500.0,
        "controller_dt_s": 0.01,
        "controller_rate_hz": 100.0,
        "physics_substeps_per_controller_step": 5,
        "sample_timing": "post_mujoco_step_plus_initial_state",
        "interpolation_used": False,
        "realtime_pacing_used": False,
        "trial_rate_hz": TRIAL_RATE_HZ,
        "trial_started_from_tick": TRIAL_NEUTRAL_START_TICK,
        "capture_first_physics_tick": 0,
        "capture_last_physics_tick": TRIAL_STOP_TICK * TRIAL_FIXED_SUBSTEPS,
        "capture_pre_edge_s": 1.0,
        "capture_post_release_s": 1.0,
    }
    if any(timing.get(key) != value for key, value in exact_timing.items()):
        raise SuiteError("simulator trace timing differs from the exact trial grid")

    reset_proof = _validate_reset_record(trace, trace_path)
    samples = trace.get("samples")
    final_physics_tick = TRIAL_STOP_TICK * TRIAL_FIXED_SUBSTEPS
    if not isinstance(samples, list) or len(samples) != final_physics_tick + 1:
        raise SuiteError("simulator trace does not contain all 2,001 trial samples")
    for index, sample in enumerate(samples):
        if not isinstance(sample, dict) or sample.get("physics_tick") != index:
            raise SuiteError("simulator trial physics ticks are not contiguous")
        time_s = sample.get("time_s")
        if (
            isinstance(time_s, bool)
            or not isinstance(time_s, (int, float))
            or not math.isclose(float(time_s), index / 500.0,
                                rel_tol=0.0, abs_tol=1e-12)
        ):
            raise SuiteError("simulator trial sample times are not on the 500 Hz grid")
        expected_control_tick = 0 if index == 0 else (index - 1) // 5
        if sample.get("control_tick") != expected_control_tick:
            raise SuiteError("simulator trial control ticks do not match the physics grid")
        if index <= TRIAL_PRESS_TICK * TRIAL_FIXED_SUBSTEPS:
            expected_command = NEUTRAL_COMMAND
            expected_phase = "neutral_pre_roll:trial_tick_0"
        elif index <= TRIAL_RELEASE_TICK * TRIAL_FIXED_SUBSTEPS:
            expected_command = motion.normalized_command
            expected_phase = "selected_command_held:trial_tick_50"
        else:
            expected_command = NEUTRAL_COMMAND
            expected_phase = "neutral_release:trial_tick_150"
        if _three_numbers(
            sample.get("normalized_command"), f"simulator sample {index} command"
        ) != expected_command or sample.get("control_phase") != expected_phase:
            raise SuiteError("simulator samples do not implement the declared single press")

    edge_time = TRIAL_PRESS_TICK / TRIAL_RATE_HZ
    first_relative = float(samples[0]["time_s"]) - edge_time
    last_relative = float(samples[-1]["time_s"]) - edge_time
    if not math.isclose(start_s, first_relative, rel_tol=0.0, abs_tol=1e-12):
        raise SuiteError("comparison start omits part of the isolated trial")
    if not math.isclose(end_s, last_relative, rel_tol=0.0, abs_tol=1e-12):
        raise SuiteError("comparison end omits part of the isolated trial")
    return {
        "state": "exact_isolated_same_reset_single_press_verified",
        "trial_protocol_identity": TRIAL_PROTOCOL_ID,
        "trial_protocol_sha256": protocol_sha,
        "edge_trial_tick": TRIAL_PRESS_TICK,
        "release_trial_tick": TRIAL_RELEASE_TICK,
        "first_physics_tick": 0,
        "last_physics_tick": final_physics_tick,
        "sample_count": len(samples),
        "first_relative_time_s": first_relative,
        "last_relative_time_s": last_relative,
        "reset": reset_proof,
        "prior_non_neutral_command_count": 0,
        "non_neutral_press_count": 1,
    }


def validate_simulator_trace_calibration(
    trace_path: Path, calibration_path: Path, expected_identity: str
) -> bool:
    """Validate simulator identity/provenance and return inline calibration state."""
    document = _load_object(trace_path, "simulator trace")
    if document.get("schema") != TRACE_SCHEMA:
        raise SuiteError(f"simulator trace {trace_path} has the wrong schema")
    command = document.get("command")
    if not isinstance(command, dict) or command.get("identity") != expected_identity:
        raise SuiteError(
            f"simulator trace {trace_path} does not identify {expected_identity}"
        )
    if document.get("source") != "clone:rek_fight_engineai":
        raise SuiteError(
            f"simulator trace {trace_path} is not the pinned EngineAI exporter"
        )
    for key in ("build_fingerprint", "capture_id", "schedule_run_id"):
        value = document.get(key)
        if not isinstance(value, str) or not value.strip():
            raise SuiteError(f"simulator trace {trace_path} has no {key}")
    if command.get("execution_state") != "simulated":
        raise SuiteError("simulator command execution_state is not simulated")
    controller = document.get("controller")
    if not isinstance(controller, dict) or controller != {
        "controlled_fighter": "official_engineai_walking_policy",
        "opponent": "official_engineai_walking_policy_approach_dummy",
        "automatic_getup": "official_engineai_supine_to_stance_policy",
        "combat_moves_enabled": False,
    }:
        raise SuiteError("simulator controller declaration is not the pinned policy set")
    explicit = _load_object(calibration_path, "simulator calibration")
    provenance = document.get("artifact_provenance")
    if not isinstance(provenance, dict):
        raise SuiteError("simulator trace has no artifact provenance")
    sdk_commit = provenance.get("engineai_sdk_commit")
    if sdk_commit != ENGINEAI_SDK_COMMIT:
        raise SuiteError("simulator trace has the wrong EngineAI SDK commit")
    verified: dict[str, dict[str, Any]] = {}
    for label in (
        "model",
        "walking_policy",
        "recovery_policy",
        "recovery_trajectory",
        "calibration",
        "controller_adapter",
        "exporter",
    ):
        record = provenance.get(label)
        if not isinstance(record, dict):
            raise SuiteError(f"simulator artifact provenance has no {label}")
        verified[label] = _artifact_from_provenance(
            trace_path, record, "path", "sha256", f"simulator trace {label}"
        )
    if verified["calibration"]["sha256"] != _sha256(calibration_path):
        raise SuiteError("simulator trace provenance binds a different calibration")
    sim_provenance = explicit.get("provenance")
    if not isinstance(sim_provenance, dict):
        raise SuiteError("explicit simulator calibration has no provenance")
    expected_model_sha = sim_provenance.get("artifact_sha256")
    if verified["model"]["sha256"] != expected_model_sha:
        raise SuiteError("simulator trace model differs from the calibrated arena MJCF")
    expected_artifact_hashes = {
        "walking_policy": WALKING_POLICY_SHA256,
        "recovery_policy": RECOVERY_POLICY_SHA256,
        "recovery_trajectory": RECOVERY_TRAJECTORY_SHA256,
    }
    for label, expected_sha in expected_artifact_hashes.items():
        if verified[label]["sha256"] != expected_sha:
            raise SuiteError(f"simulator trace has the wrong pinned {label}")
    expected_exporter = (
        Path(__file__).resolve().parent.parent.parent
        / "rek_fight"
        / "export_motion_trace.py"
    ).resolve()
    if Path(verified["exporter"]["path"]) != expected_exporter:
        raise SuiteError("simulator trace was not produced by this pinned exporter path")
    expected_adapter = expected_exporter.with_name("engineai_t800_policy.py")
    if Path(verified["controller_adapter"]["path"]) != expected_adapter:
        raise SuiteError("simulator trace has the wrong controller adapter path")
    claims = document.get("claims")
    if (
        not isinstance(claims, dict)
        or claims.get("combat_trajectory_present") is not False
        or claims.get("screen_coordinates_present") is not True
    ):
        raise SuiteError(
            "simulator trace must declare measured screen coordinates and no combat trace"
        )
    inline = document.get("calibration")
    if inline is None:
        return False
    if not isinstance(inline, dict) or _canonical(inline) != _canonical(explicit):
        raise SuiteError(
            f"simulator trace {trace_path} inline calibration differs from the "
            "required explicit simulator calibration"
        )
    return True


def _mapping(values: Iterable[tuple[str, Path]], label: str) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for selector, path in values:
        if selector in result:
            raise SuiteError(f"duplicate {label} selector {selector!r}")
        result[selector] = path
    missing = sorted(set(MOTION_SELECTORS) - set(result))
    extra = sorted(set(result) - set(MOTION_SELECTORS))
    if missing or extra:
        raise SuiteError(
            f"{label} must enumerate exactly {list(MOTION_SELECTORS)}; "
            f"missing={missing}, extra={extra}"
        )
    return result


def _selector_path(value: str) -> tuple[str, Path]:
    selector, separator, raw_path = value.partition("=")
    if not separator or not selector or not raw_path:
        raise argparse.ArgumentTypeError("value must be SELECTOR=PATH")
    return selector, Path(raw_path)


class InvocationRecorder:
    def __init__(self, output_dir: Path, tools: dict[str, Path]):
        self.output_dir = output_dir
        self.command_dir = output_dir / "commands"
        self.command_dir.mkdir()
        self.tools = tools
        self.records: list[dict[str, Any]] = []

    def run(self, tool_name: str, arguments: Sequence[str], label: str) -> ToolResult:
        tool = self.tools[tool_name]
        command = [sys.executable, str(tool), *map(str, arguments)]
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        record = {
            "schema": "rek.motion_parity_tool_invocation.v1",
            "sequence": len(self.records) + 1,
            "label": label,
            "tool": {"name": tool_name, **_identity(tool)},
            "argv": command,
            "shell_used": False,
            "exit_code": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
        }
        log_path = self.command_dir / f"{record['sequence']:04d}-{label}.json"
        _write_json_exclusive(log_path, record)
        record["record_path"] = str(log_path.resolve())
        record["record_sha256"] = _sha256(log_path)
        self.records.append(record)
        return ToolResult(
            exit_code=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
            record=record,
        )


def _write_json_exclusive(path: Path, value: Any) -> None:
    if path.exists() or path.is_symlink():
        raise FileExistsError(f"refusing to overwrite {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    payload = json.dumps(
        value, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False
    ).encode("utf-8") + b"\n"
    try:
        with temporary.open("xb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.link(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _comparison_arguments(
    config: SuiteConfig,
    rek_traces: Sequence[Path],
    sim_trace: Path,
    report_path: Path,
    *,
    sim_has_inline_calibration: bool,
    rek_video: Path | None = None,
    sim_video: Path | None = None,
    video_out: Path | None = None,
    rek_anchor: Path | None = None,
    sim_anchor: Path | None = None,
) -> list[str]:
    arguments = [
        "--rek", str(rek_traces[0]),
        "--sim", str(sim_trace),
        "--out", str(report_path),
        "--rek-calibration", str(config.rek_calibration),
        "--rek-pilot", config.rek_pilot,
        "--sim-pilot", config.sim_pilot,
        "--edge-event", "command_edge",
        "--accept-at", config.accept_at,
        "--start-s", repr(config.start_s),
        "--end-s", repr(config.end_s),
        "--fps", repr(config.comparison_fps),
        "--max-timestamp-uncertainty-s",
        repr(config.maximum_timestamp_uncertainty_s),
        "--require-screen" if config.screen_required else "--no-require-screen",
    ]
    for repeat in rek_traces[1:]:
        arguments.extend(("--rek-repeat", str(repeat)))
    if not sim_has_inline_calibration:
        arguments.extend(("--sim-calibration", str(config.sim_calibration)))
    video_values = (rek_video, sim_video, video_out, rek_anchor, sim_anchor)
    if any(value is not None for value in video_values):
        if not all(value is not None for value in video_values):
            raise AssertionError("video comparison arguments must be atomic")
        arguments.extend((
            "--rek-video", str(rek_video),
            "--sim-video", str(sim_video),
            "--video-out", str(video_out),
            "--video-layout", config.video_layout,
            "--video-fps", repr(config.video_fps),
            "--rek-video-anchor", str(rek_anchor),
            "--sim-video-anchor", str(sim_anchor),
        ))
    return arguments


def _validate_preflight_report(
    report_path: Path,
    motion: MotionSpec,
    exit_code: int,
    config: SuiteConfig,
    rek_traces: Sequence[Path],
    sim_trace: Path,
) -> tuple[str, dict[str, Any]]:
    if not report_path.is_file():
        return "insufficient_evidence", {
            "blockers": ["comparison_report_not_produced"],
            "tool_exit_code": exit_code,
        }
    report = _load_object(report_path, "comparison report")
    verdict = report.get("verdict")
    if report.get("schema") != COMPARISON_SCHEMA or not isinstance(verdict, dict):
        raise SuiteError("comparison tool emitted an invalid report schema")
    if report.get("command_identity") != motion.command_identity:
        raise SuiteError("comparison report command identity changed")
    state = verdict.get("state")
    passed = verdict.get("passed")
    expected_exit = {"passed": 0, "failed": 1, "insufficient_evidence": 2}
    if state not in expected_exit or expected_exit[state] != exit_code:
        raise SuiteError(
            f"comparison report state {state!r} disagrees with exit {exit_code}"
        )
    expected_passed = {"passed": True, "failed": False, "insufficient_evidence": None}
    if passed is not expected_passed[state]:
        raise SuiteError("comparison report verdict state/passed fields disagree")
    inputs = report.get("inputs")
    if not isinstance(inputs, dict):
        raise SuiteError("comparison report has no bound input identities")
    reference = inputs.get("reference")
    repeats = inputs.get("repeats")
    candidate = inputs.get("candidate")
    if not isinstance(reference, dict) or not isinstance(repeats, list):
        raise SuiteError("comparison report REK input identities are incomplete")
    if not isinstance(candidate, dict):
        raise SuiteError("comparison report simulator identity is incomplete")
    rek_inputs = [reference, *repeats]
    if len(rek_inputs) != len(rek_traces):
        raise SuiteError("comparison report changed the REK repeat count")
    for index, (identity, path) in enumerate(zip(rek_inputs, rek_traces)):
        if (
            identity.get("path") != str(path.resolve())
            or identity.get("sha256") != _sha256(path)
            or identity.get("format") != "REKTRACE.v1"
            or identity.get("source") != "rek"
            or identity.get("command_identity") != motion.command_identity
        ):
            raise SuiteError(f"comparison report REK input {index} was substituted")
    if (
        candidate.get("path") != str(sim_trace.resolve())
        or candidate.get("sha256") != _sha256(sim_trace)
        or candidate.get("format") != TRACE_SCHEMA
        or candidate.get("source") != "clone:rek_fight_engineai"
        or candidate.get("command_identity") != motion.command_identity
        or candidate.get("execution_state") != "simulated"
    ):
        raise SuiteError("comparison report simulator input was substituted")
    all_inputs = [*rek_inputs, candidate]
    for key in ("capture_id", "run_id", "build_fingerprint"):
        values = [identity.get(key) for identity in all_inputs]
        if any(not isinstance(value, str) or not value for value in values):
            raise SuiteError(f"comparison report has missing input {key}")
        if key != "build_fingerprint" and len(set(values)) != len(values):
            raise SuiteError(f"comparison report input {key} values are not distinct")
        if key == "build_fingerprint" and len(set(values)) != 1:
            raise SuiteError("comparison report inputs identify different REK builds")
    alignment = report.get("alignment")
    expected_frames = round((config.end_s - config.start_s) * config.comparison_fps) + 1
    if (
        not isinstance(alignment, dict)
        or alignment.get("source") != "explicit_uniform_timebase"
        or alignment.get("fps") != config.comparison_fps
        or alignment.get("start_relative_time_s") != config.start_s
        or alignment.get("end_relative_time_s") != config.end_s
        or alignment.get("frame_count") != expected_frames
        or alignment.get("interpolation_used") is not False
        or alignment.get("sample_selection")
        != "nearest_distinct_measured_sample_no_interpolation"
        or alignment.get("declared_maximum_timestamp_uncertainty_s") != 0.0
    ):
        raise SuiteError("comparison report did not preserve the exact explicit grid")
    if expected_frames < 2:
        raise SuiteError("comparison report contains fewer than two frames")
    if state == "passed" and any(
        identity.get("execution_state") != "measured_executed"
        for identity in rek_inputs
    ):
        raise SuiteError("passing report does not contain measured-executed REK inputs")
    screen = report.get("screen_metric")
    if (
        not isinstance(screen, dict)
        or screen.get("required") is not True
        or (state == "passed" and screen.get("comparable") is not True)
    ):
        raise SuiteError("comparison report bypassed the common screen-frame gate")
    return state, report


def _validate_generated_anchor(
    anchor_path: Path,
    trace_path: Path,
    video_path: Path,
    capture_dir: Path,
    marker_contract_path: Path,
    capture_schema: str,
    command_identity: str,
) -> dict[str, Any]:
    anchor = _load_object(anchor_path, "generated video clock anchor")
    if anchor.get("schema") != ANCHOR_SCHEMA:
        raise SuiteError("generated anchor has the wrong schema")
    if anchor.get("trace_sha256") != _sha256(trace_path):
        raise SuiteError("generated anchor is not bound to the compared trace")
    if anchor.get("video_sha256") != _sha256(video_path):
        raise SuiteError("generated anchor is not bound to the explicit video")
    if anchor.get("command_identity") != command_identity:
        raise SuiteError("generated anchor has the wrong command identity")
    if anchor.get("schedule_run_id") != anchor.get("run_id"):
        raise SuiteError("generated anchor run identifiers disagree")
    measurement = anchor.get("measurement")
    marker = anchor.get("marker_observation")
    verified = anchor.get("verified_artifacts")
    if not isinstance(measurement, dict):
        raise SuiteError("generated anchor has no measurement record")
    if measurement.get("state") != "measured":
        raise SuiteError("generated anchor is not measured")
    if measurement.get("method") != MEASURED_ANCHOR_METHOD:
        raise SuiteError("diagnostic or manual video clock anchor refused")
    if not isinstance(marker, dict) or marker.get("transition") != MEASURED_MARKER_TRANSITION:
        raise SuiteError("generated anchor lacks the exact rendered-marker transition")
    if not isinstance(verified, dict):
        raise SuiteError("generated anchor lacks verified artifacts")
    source_capture = anchor.get("source_capture")
    manifest_path = capture_dir / "capture.manifest.json"
    if (
        not isinstance(source_capture, dict)
        or source_capture.get("capture_schema") != capture_schema
        or source_capture.get("capture_manifest_sha256") != _sha256(manifest_path)
        or not isinstance(source_capture.get("capture_id"), str)
        or not source_capture.get("capture_id")
    ):
        raise SuiteError("generated anchor is not bound to the explicit capture")
    binding = anchor.get("capture_binding")
    expected_binding = {
        "marker_contract_schema": "rek.rendered_command_marker.v1",
        "marker_contract_sha256": _sha256(marker_contract_path),
        "trace_sha256": _sha256(trace_path),
        "capture_id": source_capture["capture_id"],
        "schedule_run_id": anchor.get("schedule_run_id"),
        "command_identity": command_identity,
        "render_binding": (
            "first_post_marker_frame_is_first_rendered_frame_after_command_edge"
        ),
    }
    if not isinstance(binding, dict) or any(
        binding.get(key) != value for key, value in expected_binding.items()
    ):
        raise SuiteError("generated anchor capture binding is incomplete or swapped")
    published = verified.get("published_video")
    if not isinstance(published, dict):
        raise SuiteError("generated anchor lacks its published-video binding")
    if Path(str(published.get("path"))).resolve() != video_path.resolve():
        raise SuiteError("capture encoded video differs from the explicit video path")
    return anchor


def _validate_final_report(
    report_path: Path,
    clip_path: Path,
    motion: MotionSpec,
    config: SuiteConfig,
    rek_traces: Sequence[Path],
    sim_trace: Path,
    rek_video_path: Path,
    sim_video_path: Path,
) -> dict[str, Any]:
    state, report = _validate_preflight_report(
        report_path, motion, 0, config, rek_traces, sim_trace
    )
    if state != "passed":
        raise SuiteError("final report is not a passing exact-grid comparison")
    verdict = report.get("verdict")
    video = report.get("video")
    if report.get("schema") != COMPARISON_SCHEMA:
        raise SuiteError("final report has the wrong schema")
    if report.get("command_identity") != motion.command_identity:
        raise SuiteError("final report has the wrong command identity")
    if not isinstance(verdict, dict) or verdict.get("state") != "passed":
        raise SuiteError("final comparison did not pass")
    if verdict.get("passed") is not True or verdict.get("blockers") != []:
        raise SuiteError("final comparison is not an unblocked passing verdict")
    required_metrics = ["root_position", "root_yaw", "screen_root"]
    metrics = report.get("metrics")
    if not isinstance(metrics, dict):
        raise SuiteError("final report has no metrics")
    for name in required_metrics:
        metric = metrics.get(name)
        if (
            not isinstance(metric, dict)
            or metric.get("passed") is not True
            or metric.get("failed_frame_count") != 0
        ):
            raise SuiteError(f"final {name} metric did not pass every measured frame")
    alignment = report.get("alignment")
    if (
        not isinstance(alignment, dict)
        or alignment.get("interpolation_used") is not False
        or alignment.get("sample_selection")
        != "nearest_distinct_measured_sample_no_interpolation"
    ):
        raise SuiteError("final comparison did not use distinct measured samples")
    if (
        not isinstance(video, dict)
        or video.get("status") != "rendered"
        or video.get("evidence_grade") != "acceptance"
        or video.get("supports_parity_verdict") is not True
        or video.get("alignment_basis") != "measured_video_clock_anchors"
        or video.get("layout") != "side-by-side"
        or video.get("fps") != config.video_fps
    ):
        raise SuiteError("paired video is not acceptance-grade measured alignment")
    expected_frames = (
        math.floor((config.end_s - config.start_s) * config.video_fps + 1e-12)
        + 1
    )
    if video.get("frame_count") != expected_frames:
        raise SuiteError("paired video does not cover every requested video frame")
    reference_video = video.get("reference_video")
    candidate_video = video.get("candidate_video")
    if not isinstance(reference_video, dict) or not isinstance(candidate_video, dict):
        raise SuiteError("paired video source identities are absent")
    if (
        reference_video.get("sha256") != _sha256(rek_video_path)
        or candidate_video.get("sha256") != _sha256(sim_video_path)
        or reference_video.get("sha256") == candidate_video.get("sha256")
    ):
        raise SuiteError("paired video sources are swapped or identical")
    reference_probe = reference_video.get("probe")
    candidate_probe = candidate_video.get("probe")
    if not isinstance(reference_probe, dict) or not isinstance(candidate_probe, dict):
        raise SuiteError("paired video source probes are absent")
    source_geometry = (
        reference_probe.get("width"),
        reference_probe.get("height"),
        reference_probe.get("r_frame_rate"),
    )
    if source_geometry != (
        candidate_probe.get("width"),
        candidate_probe.get("height"),
        candidate_probe.get("r_frame_rate"),
    ):
        raise SuiteError("paired video would rescale or rate-convert a source")
    if not math.isclose(
        _rate_hz(source_geometry[2], "source video frame rate"),
        config.video_fps,
        rel_tol=0.0,
        abs_tol=1e-12,
    ):
        raise SuiteError("paired video output rate differs from its source videos")
    output = video.get("output")
    if not isinstance(output, dict) or not clip_path.is_file():
        raise SuiteError("paired video output is absent")
    if output.get("sha256") != _sha256(clip_path):
        raise SuiteError("paired video SHA-256 does not match its report")
    if Path(str(output.get("path"))).resolve() != clip_path.resolve():
        raise SuiteError("paired video path does not match its report")
    output_probe = output.get("probe")
    if (
        not isinstance(output_probe, dict)
        or output_probe.get("frame_count") != expected_frames
    ):
        raise SuiteError("paired video probe does not prove the requested frame count")
    return report


def _capture_manifest_identity(
    capture: Path,
    expected_schema: str,
    video_path: Path,
    marker_contract_path: Path,
    command_identity: str,
) -> dict[str, Any]:
    manifest_path = _file(capture / "capture.manifest.json", "capture manifest")
    manifest = _load_object(manifest_path, "capture manifest")
    if manifest.get("schema") != expected_schema or manifest.get("status") != "complete":
        raise SuiteError(f"capture is not a complete {expected_schema} artifact")
    capture_id = manifest.get("capture_id")
    request = manifest.get("request")
    result = manifest.get("result")
    binding = manifest.get("binding")
    artifacts = manifest.get("artifacts")
    if not isinstance(capture_id, str) or not capture_id:
        raise SuiteError("capture manifest has no capture_id")
    if not all(isinstance(item, dict) for item in (request, result, binding, artifacts)):
        raise SuiteError("capture manifest is missing request/result/binding/artifacts")
    assert isinstance(request, dict)
    assert isinstance(result, dict)
    assert isinstance(binding, dict)
    assert isinstance(artifacts, dict)
    if (
        request.get("synthetic_frame_duplication") is not False
        or isinstance(request.get("fps_numerator"), bool)
        or not isinstance(request.get("fps_numerator"), int)
        or request.get("fps_numerator") <= 0
        or isinstance(request.get("fps_denominator"), bool)
        or not isinstance(request.get("fps_denominator"), int)
        or request.get("fps_denominator") <= 0
        or isinstance(request.get("expected_frame_count"), bool)
        or not isinstance(request.get("expected_frame_count"), int)
        or request.get("expected_frame_count") < 2
    ):
        raise SuiteError("capture request does not prove a non-synthetic timebase")
    if expected_schema == SIM_CAPTURE_SCHEMA and (
        request.get("sample_interpolation_used") is not False
        or request.get("frame_selection")
        != "exact_measured_physics_tick_modulo_stride"
    ):
        raise SuiteError("simulator capture is not selected from exact physics samples")
    expected_count = request["expected_frame_count"]
    width = result.get("width_px")
    height = result.get("height_px")
    if (
        result.get("actual_frame_count") != expected_count
        or isinstance(width, bool)
        or not isinstance(width, int)
        or width <= 0
        or width % 2
        or isinstance(height, bool)
        or not isinstance(height, int)
        or height <= 0
        or height % 2
    ):
        raise SuiteError("capture result has invalid frame count or video geometry")
    expected_binding = {
        "marker_contract_schema": "rek.rendered_command_marker.v1",
        "marker_contract_sha256": _sha256(marker_contract_path),
        "capture_id": capture_id,
        "command_identity": command_identity,
        "render_binding": (
            "first_post_marker_frame_is_first_rendered_frame_after_command_edge"
        ),
    }
    if any(binding.get(key) != value for key, value in expected_binding.items()):
        raise SuiteError("capture manifest binding differs from the selected motion")
    for key in ("trace_sha256", "producer_sha256"):
        if not isinstance(binding.get(key), str) or not SHA256_PATTERN.fullmatch(
            binding[key]
        ):
            raise SuiteError(f"capture manifest binding has no valid {key}")
    if not isinstance(binding.get("schedule_run_id"), str) or not binding.get(
        "schedule_run_id"
    ):
        raise SuiteError("capture manifest binding has no schedule_run_id")
    marker_contract = _load_object(marker_contract_path, "marker contract")
    producer_record = marker_contract.get("producer")
    if not isinstance(producer_record, dict):
        raise SuiteError("marker contract has no producer artifact")
    producer = _artifact_from_provenance(
        marker_contract_path,
        producer_record,
        "path",
        "sha256",
        "marker contract producer",
    )
    if producer["sha256"] != binding["producer_sha256"]:
        raise SuiteError("capture binding and marker producer SHA-256 differ")
    if expected_schema == SIM_CAPTURE_SCHEMA:
        expected_sim_producer = (
            Path(__file__).resolve().parent.parent.parent
            / "rek_fight"
            / "capture_motion_video.py"
        )
        if producer["sha256"] != _sha256(expected_sim_producer):
            raise SuiteError(
                "simulator capture marker was not produced by capture_motion_video.py"
            )
    encoded = artifacts.get("encoded_video")
    if not isinstance(encoded, dict):
        raise SuiteError("capture manifest has no encoded video artifact")
    raw_video_path = encoded.get("path")
    if not isinstance(raw_video_path, str) or not raw_video_path:
        raise SuiteError("capture manifest encoded video path is absent")
    published = (capture / raw_video_path).resolve()
    if published != video_path.resolve() or encoded.get("sha256") != _sha256(video_path):
        raise SuiteError("capture manifest does not bind the explicit motion video")
    if result.get("encoded_video_sha256") != _sha256(video_path):
        raise SuiteError("capture result does not bind the explicit motion video")
    return {
        **_identity(manifest_path),
        "schema": expected_schema,
        "capture_id": capture_id,
        "schedule_run_id": binding["schedule_run_id"],
        "command_identity": command_identity,
        "fps_numerator": request["fps_numerator"],
        "fps_denominator": request["fps_denominator"],
        "frame_count": expected_count,
        "width_px": width,
        "height_px": height,
        "binding": binding,
    }


def validate_config(config: SuiteConfig) -> SuiteConfig:
    if len(config.rek_runs) < 3:
        raise SuiteError("at least three explicit REK v6 runs are required")
    raw_paths = [_file(run.raw_trace, f"REK run {index} raw trace")
                 for index, run in enumerate(config.rek_runs)]
    transcript_paths = [
        _file(run.bridge_transcript, f"REK run {index} bridge transcript")
        for index, run in enumerate(config.rek_runs)
    ]
    if len({os.path.normcase(str(path)) for path in raw_paths}) != len(raw_paths):
        raise SuiteError("REK raw trace paths must be distinct")
    if len({_sha256(path) for path in raw_paths}) != len(raw_paths):
        raise SuiteError("REK raw trace contents must be distinct captures")
    if len({os.path.normcase(str(path)) for path in transcript_paths}) != len(
        transcript_paths
    ):
        raise SuiteError("REK bridge transcript paths must be distinct")
    if len({_sha256(path) for path in transcript_paths}) != len(transcript_paths):
        raise SuiteError("REK bridge transcript contents must be distinct captures")
    output = config.output_dir.expanduser().absolute()
    if output.exists() or output.is_symlink():
        raise SuiteError(f"refusing to overwrite output directory {output}")
    _finite(config.start_s, "start_s")
    _finite(config.end_s, "end_s")
    if config.end_s <= config.start_s:
        raise SuiteError("end_s must be later than start_s")
    if config.start_s >= 0.0:
        raise SuiteError("comparison window must include measured pre-edge state")
    comparison_fps = _finite(
        config.comparison_fps, "comparison_fps", positive=True
    )
    uncertainty = _finite(
        config.maximum_timestamp_uncertainty_s,
        "maximum_timestamp_uncertainty_s",
    )
    if uncertainty != 0.0:
        raise SuiteError(
            "maximum_timestamp_uncertainty_s must be zero for exact-grid parity"
        )
    _finite(config.video_fps, "video_fps", positive=True)
    if config.accept_at not in {"median", "p95", "p99", "max"}:
        raise SuiteError("accept_at is unsupported")
    if config.video_layout != "side-by-side":
        raise SuiteError("video_layout must be side-by-side without visual blending")
    if config.screen_required is not True:
        raise SuiteError("the common measured screen-frame gate is mandatory")
    if not config.rek_pilot or not config.sim_pilot:
        raise SuiteError("both pilot selectors must be explicit non-empty strings")
    exact_maps = {
        "rek_captures": _mapping(config.rek_captures.items(), "REK captures"),
        "rek_videos": _mapping(config.rek_videos.items(), "REK videos"),
        "rek_marker_contracts": _mapping(
            config.rek_marker_contracts.items(), "REK marker contracts"
        ),
        "sim_traces": _mapping(config.sim_traces.items(), "simulator traces"),
        "sim_captures": _mapping(
            config.sim_captures.items(), "simulator captures"
        ),
        "sim_videos": _mapping(config.sim_videos.items(), "simulator videos"),
        "sim_marker_contracts": _mapping(
            config.sim_marker_contracts.items(), "simulator marker contracts"
        ),
    }
    schedule_path = _file(config.schedule_manifest, "schedule manifest")
    schedule = _load_object(schedule_path, "schedule manifest")
    schedule_rate = schedule.get("schedule_rate_hz")
    substeps = schedule.get("fixed_substeps_per_tick")
    if (
        isinstance(schedule_rate, bool)
        or not isinstance(schedule_rate, (int, float))
        or isinstance(substeps, bool)
        or not isinstance(substeps, int)
        or substeps <= 0
    ):
        raise SuiteError(
            "schedule manifest lacks numeric rate and fixed substeps per tick"
        )
    physics_rate = float(schedule_rate) * substeps
    if not math.isclose(comparison_fps, physics_rate, abs_tol=1e-12):
        raise SuiteError(
            "comparison_fps must equal the measured schedule physics rate"
        )
    if not math.isclose(config.start_s, -1.0, abs_tol=1e-12):
        raise SuiteError(
            "start_s must retain the isolated trial from neutral tick zero"
        )
    if not math.isclose(config.end_s, 3.0, abs_tol=1e-12):
        raise SuiteError(
            "end_s must retain the isolated trial through its final neutral sample"
        )
    rek_capture_paths = {
        key: _directory(path, f"REK capture {key}")
        for key, path in exact_maps["rek_captures"].items()
    }
    rek_video_paths = {
        key: _file(path, f"REK video {key}")
        for key, path in exact_maps["rek_videos"].items()
    }
    sim_capture_paths = {
        key: _directory(path, f"simulator capture {key}")
        for key, path in exact_maps["sim_captures"].items()
    }
    sim_video_paths = {
        key: _file(path, f"simulator video {key}")
        for key, path in exact_maps["sim_videos"].items()
    }
    for label, paths in (
        ("REK captures", rek_capture_paths.values()),
        ("REK videos", rek_video_paths.values()),
        ("simulator captures", sim_capture_paths.values()),
        ("simulator videos", sim_video_paths.values()),
    ):
        normalized = [os.path.normcase(str(path.resolve())) for path in paths]
        if len(set(normalized)) != len(MOTIONS):
            raise SuiteError(f"{label} must be distinct per motion edge")
    video_hashes = [
        _sha256(path) for path in (*rek_video_paths.values(), *sim_video_paths.values())
    ]
    if len(set(video_hashes)) != len(video_hashes):
        raise SuiteError("every REK and simulator motion video must have distinct bytes")
    return SuiteConfig(
        **{
            **config.__dict__,
            "rek_runs": tuple(
                RekRun(raw, transcript)
                for raw, transcript in zip(raw_paths, transcript_paths)
            ),
            "inventory": _file(config.inventory, "inventory"),
            "schedule_manifest": schedule_path,
            "rek_calibration": _file(config.rek_calibration, "REK calibration"),
            "sim_calibration": _file(
                config.sim_calibration, "simulator calibration"
            ),
            "rek_captures": rek_capture_paths,
            "rek_videos": rek_video_paths,
            "rek_marker_contracts": {
                key: _file(path, f"REK marker contract {key}")
                for key, path in exact_maps["rek_marker_contracts"].items()
            },
            "sim_traces": {
                key: _file(path, f"simulator trace {key}")
                for key, path in exact_maps["sim_traces"].items()
            },
            "sim_captures": sim_capture_paths,
            "sim_videos": sim_video_paths,
            "sim_marker_contracts": {
                key: _file(path, f"simulator marker contract {key}")
                for key, path in exact_maps["sim_marker_contracts"].items()
            },
            "output_dir": output,
        }
    )


def run_suite(config: SuiteConfig) -> tuple[int, dict[str, Any]]:
    config = validate_config(config)
    output = config.output_dir
    output.parent.mkdir(parents=True, exist_ok=True)
    output.mkdir()
    evidence_dir = Path(__file__).resolve().parent
    tools = {
        "client_fixed_import": _file(
            evidence_dir / "client_fixed_import.py", "client-fixed importer"
        ),
        "video_clock_anchor": _file(
            evidence_dir / "video_clock_anchor.py", "video clock anchor tool"
        ),
        "paired_motion_compare": _file(
            evidence_dir / "paired_motion_compare.py", "paired comparator"
        ),
    }
    invocations = InvocationRecorder(output, tools)
    report: dict[str, Any] = {
        "schema": SUITE_SCHEMA,
        "state": "in_progress",
        "passed": None,
        "blockers": [],
        "scope": {
            "motion_set": "six_controlled_fighter_root_velocity_commands",
            "motion_edges": [
                {
                    "selector": motion.selector,
                    "command_identity": motion.command_identity,
                    "simulator_command": motion.simulator_command,
                    "normalized_command": list(motion.normalized_command),
                    "rek_edge_schedule_tick": motion.rek_edge_schedule_tick,
                    "rek_release_schedule_tick": motion.rek_release_schedule_tick,
                    "simulator_trial_scope": "isolated_same_reset_single_press",
                    "simulator_edge_trial_tick": TRIAL_PRESS_TICK,
                    "simulator_release_trial_tick": TRIAL_RELEASE_TICK,
                }
                for motion in MOTIONS
            ],
            "combat_motions_evaluated": False,
            "complete_rek_moveset_claimed": False,
            "opponent_trajectory_evaluated": False,
            "joint_pose_evaluated": False,
            "contact_or_event_parity_evaluated": False,
            "full_trajectory_event_parity_claimed": False,
            "frame_perfect_video_alignment_claimed": False,
            "video_alignment_precision": (
                "machine-measured marker bracket, midpoint estimate with half-source-"
                "frame uncertainty"
            ),
        },
        "acceptance": {
            "accept_at": config.accept_at,
            "start_relative_time_s": config.start_s,
            "end_relative_time_s": config.end_s,
            "comparison_fps": config.comparison_fps,
            "maximum_timestamp_uncertainty_s": (
                config.maximum_timestamp_uncertainty_s
            ),
            "screen_metric_required": config.screen_required,
            "video_fps": config.video_fps,
            "video_layout": config.video_layout,
            "manual_clock_offsets_allowed": False,
            "interpolation_allowed": False,
            "allowance_source": "time-indexed repeated-run REK variance only",
        },
        "tools": {name: _identity(path) for name, path in tools.items()},
        "inputs": {
            "inventory": _identity(config.inventory),
            "schedule_manifest": _identity(config.schedule_manifest),
            "rek_runs": [
                {
                    "raw_trace": _identity(run.raw_trace),
                    "bridge_transcript": _identity(run.bridge_transcript),
                }
                for run in config.rek_runs
            ],
            "rek_captures": {
                selector: {
                    "path": str(config.rek_captures[selector]),
                    "video": _identity(config.rek_videos[selector]),
                }
                for selector in MOTION_SELECTORS
            },
            "rek_marker_contracts": {
                selector: _identity(path)
                for selector, path in config.rek_marker_contracts.items()
            },
        },
        "shared_arena_frame_calibration": None,
        "motions": [],
        "invocations": [],
    }

    try:
        report["shared_arena_frame_calibration"] = validate_shared_calibrations(
            config.rek_calibration, config.sim_calibration
        )
    except Exception as exc:
        report["state"] = "insufficient_evidence"
        report["passed"] = None
        report["blockers"].append({
            "code": "shared_arena_frame_calibration_not_proven",
            "detail": str(exc),
        })
        report["invocations"] = invocations.records
        _write_json_exclusive(output / "suite.report.json", report)
        return 2, report

    simulator_trial_proofs: dict[str, dict[str, Any]] = {}
    simulator_trial_errors: dict[str, str] = {}
    for motion in MOTIONS:
        try:
            simulator_trial_proofs[motion.selector] = (
                validate_simulator_isolated_trial(
                    config.sim_traces[motion.selector],
                    motion,
                    config.start_s,
                    config.end_s,
                )
            )
        except Exception as exc:
            simulator_trial_errors[motion.selector] = str(exc)
    if not simulator_trial_errors:
        reset_record_hashes = {
            proof["reset"]["record_sha256"]
            for proof in simulator_trial_proofs.values()
        }
        reset_identity_hashes = {
            proof["reset"]["identity_sha256"]
            for proof in simulator_trial_proofs.values()
        }
        if len(reset_record_hashes) != 1 or len(reset_identity_hashes) != 1:
            detail = (
                "the six simulator selectors do not start from the exact same "
                "measured composite reset"
            )
            simulator_trial_errors = {
                selector: detail for selector in MOTION_SELECTORS
            }
    report["simulator_single_press_trials"] = {
        selector: (
            {"state": "verified", "proof": simulator_trial_proofs[selector]}
            if selector not in simulator_trial_errors
            else {"state": "insufficient_evidence", "detail": simulator_trial_errors[selector]}
        )
        for selector in MOTION_SELECTORS
    }

    for motion in MOTIONS:
        motion_dir = output / "motions" / motion.slug
        rek_dir = motion_dir / "rek"
        motion_dir.mkdir(parents=True)
        rek_dir.mkdir()
        motion_record: dict[str, Any] = {
            "selector": motion.selector,
            "command_identity": motion.command_identity,
            "state": "in_progress",
            "passed": None,
            "blockers": [],
            "rek_traces": [],
            "sim_trace": _identity(config.sim_traces[motion.selector]),
            "rek_capture_manifest": None,
            "rek_video": _identity(config.rek_videos[motion.selector]),
            "sim_capture_manifest": None,
            "sim_video": _identity(config.sim_videos[motion.selector]),
            "sim_marker_contract": _identity(
                config.sim_marker_contracts[motion.selector]
            ),
            "simulator_isolated_trial": None,
            "video_clock_anchors": None,
            "comparison_report": None,
            "paired_video": None,
        }
        report["motions"].append(motion_record)
        if motion.selector in simulator_trial_errors:
            motion_record["blockers"].append({
                "code": "simulator_isolated_same_reset_single_press_not_proven",
                "detail": simulator_trial_errors[motion.selector],
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        motion_record["simulator_isolated_trial"] = simulator_trial_proofs[
            motion.selector
        ]
        try:
            motion_record["rek_capture_manifest"] = _capture_manifest_identity(
                config.rek_captures[motion.selector],
                CAPTURE_SCHEMA,
                config.rek_videos[motion.selector],
                config.rek_marker_contracts[motion.selector],
                motion.command_identity,
            )
        except Exception as exc:
            motion_record["blockers"].append({
                "code": "rek_capture_not_complete",
                "detail": str(exc),
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        try:
            motion_record["sim_capture_manifest"] = _capture_manifest_identity(
                config.sim_captures[motion.selector],
                SIM_CAPTURE_SCHEMA,
                config.sim_videos[motion.selector],
                config.sim_marker_contracts[motion.selector],
                motion.command_identity,
            )
        except Exception as exc:
            motion_record["blockers"].append({
                "code": "simulator_capture_not_complete",
                "detail": str(exc),
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        rek_capture_record = motion_record["rek_capture_manifest"]
        sim_capture_record = motion_record["sim_capture_manifest"]
        rek_capture_rate = (
            rek_capture_record["fps_numerator"]
            / rek_capture_record["fps_denominator"]
        )
        sim_capture_rate = (
            sim_capture_record["fps_numerator"]
            / sim_capture_record["fps_denominator"]
        )
        if (
            (rek_capture_record["width_px"], rek_capture_record["height_px"])
            != (sim_capture_record["width_px"], sim_capture_record["height_px"])
            or not math.isclose(rek_capture_rate, sim_capture_rate, abs_tol=1e-12)
            or not math.isclose(rek_capture_rate, config.video_fps, abs_tol=1e-12)
        ):
            motion_record["blockers"].append({
                "code": "motion_video_geometry_or_rate_not_identical",
                "rek": {
                    "width_px": rek_capture_record["width_px"],
                    "height_px": rek_capture_record["height_px"],
                    "fps": rek_capture_rate,
                },
                "simulator": {
                    "width_px": sim_capture_record["width_px"],
                    "height_px": sim_capture_record["height_px"],
                    "fps": sim_capture_rate,
                },
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        imported: list[Path] = []
        for index, run in enumerate(config.rek_runs, 1):
            imported_path = rek_dir / f"run-{index}.rektrace"
            result = invocations.run(
                "client_fixed_import",
                (
                    "--raw", str(run.raw_trace),
                    "--inventory", str(config.inventory),
                    "--out", str(imported_path),
                    "--control-log", str(run.bridge_transcript),
                    "--schedule-manifest", str(config.schedule_manifest),
                    "--motion-edge", motion.selector,
                ),
                f"import-{motion.slug}-run-{index}",
            )
            if result.exit_code != 0 or not imported_path.is_file():
                motion_record["blockers"].append({
                    "code": "rek_v6_import_failed",
                    "run_index": index,
                    "tool_exit_code": result.exit_code,
                    "invocation": result.record["record_path"],
                })
            else:
                imported.append(imported_path)
                motion_record["rek_traces"].append(_identity(imported_path))
        if len(imported) != len(config.rek_runs):
            motion_record["state"] = "insufficient_evidence"
            continue

        try:
            sim_inline = validate_simulator_trace_calibration(
                config.sim_traces[motion.selector],
                config.sim_calibration,
                motion.command_identity,
            )
        except Exception as exc:
            motion_record["blockers"].append({
                "code": "simulator_trace_calibration_not_explicitly_bound",
                "detail": str(exc),
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        motion_record["simulator_calibration_source"] = (
            "inline_exactly_equals_explicit_calibration"
            if sim_inline else "explicit_calibration_file"
        )

        preflight_path = motion_dir / "preflight.comparison.json"
        preflight = invocations.run(
            "paired_motion_compare",
            _comparison_arguments(
                config,
                imported,
                config.sim_traces[motion.selector],
                preflight_path,
                sim_has_inline_calibration=sim_inline,
            ),
            f"compare-preflight-{motion.slug}",
        )
        try:
            state, preflight_report = _validate_preflight_report(
                preflight_path,
                motion,
                preflight.exit_code,
                config,
                imported,
                config.sim_traces[motion.selector],
            )
        except Exception as exc:
            motion_record["blockers"].append({
                "code": "preflight_comparator_output_invalid",
                "detail": str(exc),
                "tool_exit_code": preflight.exit_code,
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        motion_record["preflight_report"] = _identity(preflight_path)
        if state != "passed":
            motion_record["state"] = state
            motion_record["passed"] = preflight_report["verdict"]["passed"]
            motion_record["blockers"] = preflight_report["verdict"]["blockers"]
            motion_record["comparison_report"] = _identity(preflight_path)
            continue

        rek_anchor_path = motion_dir / "rek.video-clock-anchor.json"
        sim_anchor_path = motion_dir / "sim.video-clock-anchor.json"
        rek_anchor_result = invocations.run(
            "video_clock_anchor",
            (
                "--capture", str(config.rek_captures[motion.selector]),
                "--marker-contract",
                str(config.rek_marker_contracts[motion.selector]),
                "--out", str(rek_anchor_path),
            ),
            f"anchor-rek-{motion.slug}",
        )
        sim_anchor_result = invocations.run(
            "video_clock_anchor",
            (
                "--capture", str(config.sim_captures[motion.selector]),
                "--marker-contract",
                str(config.sim_marker_contracts[motion.selector]),
                "--out", str(sim_anchor_path),
            ),
            f"anchor-sim-{motion.slug}",
        )
        if rek_anchor_result.exit_code != 0 or sim_anchor_result.exit_code != 0:
            motion_record["blockers"].append({
                "code": "measured_video_clock_anchor_failed",
                "rek_exit_code": rek_anchor_result.exit_code,
                "sim_exit_code": sim_anchor_result.exit_code,
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        try:
            _validate_generated_anchor(
                rek_anchor_path,
                imported[0],
                config.rek_videos[motion.selector],
                config.rek_captures[motion.selector],
                config.rek_marker_contracts[motion.selector],
                CAPTURE_SCHEMA,
                motion.command_identity,
            )
            _validate_generated_anchor(
                sim_anchor_path,
                config.sim_traces[motion.selector],
                config.sim_videos[motion.selector],
                config.sim_captures[motion.selector],
                config.sim_marker_contracts[motion.selector],
                SIM_CAPTURE_SCHEMA,
                motion.command_identity,
            )
            motion_record["video_clock_anchors"] = {
                "rek": _identity(rek_anchor_path),
                "simulator": _identity(sim_anchor_path),
            }
        except Exception as exc:
            motion_record["blockers"].append({
                "code": "diagnostic_manual_or_unbound_video_anchor_refused",
                "detail": str(exc),
            })
            motion_record["state"] = "insufficient_evidence"
            continue

        final_path = motion_dir / "comparison.json"
        clip_path = motion_dir / "paired.mp4"
        final = invocations.run(
            "paired_motion_compare",
            _comparison_arguments(
                config,
                imported,
                config.sim_traces[motion.selector],
                final_path,
                sim_has_inline_calibration=sim_inline,
                rek_video=config.rek_videos[motion.selector],
                sim_video=config.sim_videos[motion.selector],
                video_out=clip_path,
                rek_anchor=rek_anchor_path,
                sim_anchor=sim_anchor_path,
            ),
            f"compare-video-{motion.slug}",
        )
        if final.exit_code != 0:
            if clip_path.is_file():
                motion_record["discarded_unaccepted_clip_sha256"] = _sha256(
                    clip_path
                )
                clip_path.unlink()
            motion_record["blockers"].append({
                "code": "acceptance_video_comparison_failed",
                "tool_exit_code": final.exit_code,
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        try:
            final_report = _validate_final_report(
                final_path,
                clip_path,
                motion,
                config,
                imported,
                config.sim_traces[motion.selector],
                config.rek_videos[motion.selector],
                config.sim_videos[motion.selector],
            )
        except Exception as exc:
            if clip_path.is_file():
                motion_record["discarded_unaccepted_clip_sha256"] = _sha256(
                    clip_path
                )
                clip_path.unlink()
            motion_record["blockers"].append({
                "code": "acceptance_video_report_invalid",
                "detail": str(exc),
            })
            motion_record["state"] = "insufficient_evidence"
            continue
        motion_record["state"] = "passed"
        motion_record["passed"] = True
        motion_record["comparison_report"] = _identity(final_path)
        motion_record["paired_video"] = _identity(clip_path)
        motion_record["metrics"] = final_report["metrics"]

    states = [motion["state"] for motion in report["motions"]]
    if all(state == "passed" for state in states):
        report["state"] = "passed"
        report["passed"] = True
    elif any(state == "insufficient_evidence" for state in states):
        report["state"] = "insufficient_evidence"
        report["passed"] = None
        report["blockers"].append("one_or_more_motion_edges_lack_acceptance_evidence")
    else:
        report["state"] = "failed"
        report["passed"] = False
        report["blockers"].append("one_or_more_motion_edges_exceed_rek_variance")
    report["invocations"] = [
        {
            "sequence": record["sequence"],
            "label": record["label"],
            "exit_code": record["exit_code"],
            "record_path": record["record_path"],
            "record_sha256": record["record_sha256"],
        }
        for record in invocations.records
    ]
    suite_path = output / "suite.report.json"
    _write_json_exclusive(suite_path, report)
    print(f"suite: {report['state']}")
    print(f"motions: {len(report['motions'])}")
    print(f"report: {suite_path.resolve()}")
    print(f"report sha256: {_sha256(suite_path)}")
    if report["passed"] is True:
        return 0, report
    if report["passed"] is False:
        return 1, report
    return 2, report


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rek-run",
        action="append",
        nargs=2,
        required=True,
        metavar=("RAW_V6_TRACE", "BRIDGE_TRANSCRIPT"),
        help="repeat for at least three distinct completed REK captures",
    )
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--schedule-manifest", type=Path, required=True)
    parser.add_argument("--rek-calibration", type=Path, required=True)
    parser.add_argument("--sim-calibration", type=Path, required=True)
    parser.add_argument("--rek-pilot", required=True)
    parser.add_argument("--sim-pilot", required=True)
    parser.add_argument(
        "--rek-capture",
        action="append",
        type=_selector_path,
        required=True,
        metavar="SELECTOR=CAPTURE_DIR",
    )
    parser.add_argument(
        "--rek-video",
        action="append",
        type=_selector_path,
        required=True,
        metavar="SELECTOR=VIDEO_MP4",
    )
    parser.add_argument(
        "--rek-marker-contract", action="append", type=_selector_path, required=True
    )
    parser.add_argument("--sim-trace", action="append", type=_selector_path, required=True)
    parser.add_argument(
        "--sim-capture", action="append", type=_selector_path, required=True
    )
    parser.add_argument("--sim-video", action="append", type=_selector_path, required=True)
    parser.add_argument(
        "--sim-marker-contract", action="append", type=_selector_path, required=True
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--accept-at", choices=("median", "p95", "p99", "max"), required=True
    )
    parser.add_argument("--start-s", type=float, required=True)
    parser.add_argument("--end-s", type=float, required=True)
    parser.add_argument("--comparison-fps", type=float, required=True)
    parser.add_argument(
        "--max-timestamp-uncertainty-s", type=float, required=True
    )
    parser.add_argument(
        "--screen-gate", choices=("required",), required=True
    )
    parser.add_argument("--video-fps", type=float, required=True)
    parser.add_argument(
        "--video-layout", choices=("side-by-side",), required=True
    )
    return parser


def config_from_args(arguments: argparse.Namespace) -> SuiteConfig:
    return SuiteConfig(
        rek_runs=tuple(
            RekRun(Path(raw), Path(transcript))
            for raw, transcript in arguments.rek_run
        ),
        inventory=arguments.inventory,
        schedule_manifest=arguments.schedule_manifest,
        rek_calibration=arguments.rek_calibration,
        sim_calibration=arguments.sim_calibration,
        rek_pilot=arguments.rek_pilot,
        sim_pilot=arguments.sim_pilot,
        rek_captures=_mapping(arguments.rek_capture, "REK captures"),
        rek_videos=_mapping(arguments.rek_video, "REK videos"),
        rek_marker_contracts=_mapping(
            arguments.rek_marker_contract, "REK marker contracts"
        ),
        sim_traces=_mapping(arguments.sim_trace, "simulator traces"),
        sim_captures=_mapping(arguments.sim_capture, "simulator captures"),
        sim_videos=_mapping(arguments.sim_video, "simulator videos"),
        sim_marker_contracts=_mapping(
            arguments.sim_marker_contract, "simulator marker contracts"
        ),
        output_dir=arguments.out,
        accept_at=arguments.accept_at,
        start_s=arguments.start_s,
        end_s=arguments.end_s,
        comparison_fps=arguments.comparison_fps,
        maximum_timestamp_uncertainty_s=arguments.max_timestamp_uncertainty_s,
        screen_required=arguments.screen_gate == "required",
        video_fps=arguments.video_fps,
        video_layout=arguments.video_layout,
    )


def main(argv: Sequence[str] | None = None) -> int:
    try:
        arguments = build_parser().parse_args(argv)
        config = config_from_args(arguments)
        exit_code, _ = run_suite(config)
        return exit_code
    except (FileExistsError, OSError, SuiteError, ValueError) as exc:
        print(f"motion parity suite failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
