[base]
env_name = robocode
checkpoint_interval = 100

[vec]
total_agents = 4096
num_buffers = 4
num_threads = 4
num_frozen_banks = 1
frozen_bank_pct = 0.1

[selfplay]
enabled = 1
max_size = 100
swap_winrate = 0.8
min_games = 2048
elo_init = 0
elo_k = 16
seed = 42
snapshot_interval = 200000000
opp_timeout_steps = 100000000

[env]
num_agents = 2
num_bots = 0
width = 800
height = 600
reward_damage = 0.0
reward_spot = 0.0
dr = 0.181647854498119
bot_policy = 1
max_ticks = 3000

[policy]
hidden_size = 256
num_layers = 3

[train]
gpus = 1
seed = 42
total_timesteps = 4_000_000_000
learning_rate = 0.01
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.9998480946489037
gae_lambda = 0.9786838910227905
horizon = 256

[sweep]
match_enemy_model_path = 'resources/robocode/best_robo.bin'
match_num_games = 4096
match_max_ticks = 4096
match_enemy_hidden_size = 1024
match_enemy_num_layers = 2.69591
bot_eval = True
bot_eval_episodes = 32768
bot_eval_envs = 4096
bot_eval_burnin_episodes = 4096
bot_eval_policy = -1
bot_eval_max_ticks = 0
downsample = 1
metric = bot_perf

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e8
max = 1e9
mean = 5e8
scale = auto

#[sweep.env.reward_damage]
#distribution = uniform
#min = 0.0
#max = 0.1
#mean = 0.01
#scale = auto

#[sweep.env.reward_spot]
#distribution = uniform
#min = 0.0
#max = 0.01
#mean = 0.001
#scale = auto

[sweep.env.dr]
distribution = uniform
min = 0.0
max = 0.6
mean = 0.3
scale = auto
