/* Emits the colosseum item observation table that colo_ent_gather_inv reads.
 *
 * src/ocean.cu deliberately sees no OSRS header, so the twelve per-cell features that are a
 * pure function of the item cannot be computed there. They are baked here instead, by calling
 * the same osrs_write_inventory_cell_affordance_features_compact the observation used to call,
 * one row per cell code.
 *
 *   cc -std=c11 -O2 -I. -o /tmp/gen_colo_item_obs \
 *      ocean/osrs/tools/gen_colosseum_item_obs_table.c -lm
 *   /tmp/gen_colo_item_obs ocean/osrs/osrs_colosseum_item_obs_generated.h \
 *                          ocean/osrs/osrs_colosseum_item_obs_table.inc
 *
 * test_colosseum_modifiers rebuilds every row in memory and diffs it against the committed
 * table, so a stale checkout fails the battery instead of training on wrong observations.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ocean/osrs/osrs_inventory_clicks.h"

/* encounter_init_maxed_player_combat_stats(&s->player, COLO_PLAYER_PRAYER_LEVEL) at reset.
 * encounter_colosseum_obs_mask.inc static_asserts both against the encounter's own values. */
#define GEN_BASE_PRAYER 99
#define GEN_BASE_LEVEL MAXED_BASE_ATTACK

/* Frailty rewrites base_hitpoints mid-episode, so hp_heal cannot be baked. It is the reason
 * the observation still carries one float per cell. Prove the table is free of it by building
 * every row at two hitpoint levels and rejecting any row that moves. */
#define GEN_PROBE_HITPOINTS_A MAXED_BASE_HITPOINTS
#define GEN_PROBE_HITPOINTS_B 60

static void emit_float(FILE* out, float v) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%.9g", (double)v);
    if (!strpbrk(buf, ".eEnN")) strncat(buf, ".0", sizeof(buf) - strlen(buf) - 1);
    fprintf(out, "%sf", buf);
}

static void build_row(float* row, int code, int base_hitpoints) {
    osrs_write_inventory_cell_obs_table_row(
        row, code, base_hitpoints, GEN_BASE_PRAYER, GEN_BASE_LEVEL);
}

static void require_code_round_trip(int code) {
    OsrsInventoryCell cell = osrs_inventory_cell_for_obs_code(code);
    int back = osrs_inventory_cell_obs_code(cell.item_idx, cell.raw_osrs_id);
    if (back == code) return;
    fprintf(stderr,
        "colosseum item obs table: code %d resolves to item %u raw %u, which codes back as "
        "%d. Two codes share one cell content and the table is not a function of the code.\n",
        code, cell.item_idx, cell.raw_osrs_id, back);
    exit(1);
}

static void require_hitpoints_free(int code) {
    float a[OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT];
    float b[OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT];
    build_row(a, code, GEN_PROBE_HITPOINTS_A);
    build_row(b, code, GEN_PROBE_HITPOINTS_B);

    for (int f = 0; f < OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT; f++) {
        if (a[f] == b[f]) continue;
        fprintf(stderr,
            "colosseum item obs table: code %d feature %d depends on base_hitpoints "
            "(%g at %d, %g at %d). Ship it in the observation or key the table on it.\n",
            code, f, (double)a[f], GEN_PROBE_HITPOINTS_A,
            (double)b[f], GEN_PROBE_HITPOINTS_B);
        exit(1);
    }
}

static FILE* open_or_die(const char* path) {
    FILE* f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "colosseum item obs table: cannot write %s\n", path);
        exit(1);
    }
    return f;
}

static void write_header(const char* path) {
    FILE* out = open_or_die(path);
    fprintf(out,
        "/* Generated by ocean/osrs/tools/gen_colosseum_item_obs_table.c. Do not edit.\n"
        " * Dependency-free on purpose: src/ocean.cu includes it and no OSRS header. */\n"
        "#ifndef OSRS_COLOSSEUM_ITEM_OBS_GENERATED_H\n"
        "#define OSRS_COLOSSEUM_ITEM_OBS_GENERATED_H\n"
        "\n"
        "#define COLO_ITEM_OBS_TABLE_ROWS %d\n"
        "#define COLO_ITEM_OBS_TABLE_COLS %d\n"
        "#define COLO_ITEM_OBS_TABLE_BASE_PRAYER %d\n"
        "#define COLO_ITEM_OBS_TABLE_BASE_LEVEL %d\n"
        "\n"
        "/* The observation carries code/SCALE; multiply back to index a row. A power of two\n"
        " * keeps the round trip exact in bf16 and keeps the code out of the global linear\n"
        " * layer's dynamic range. */\n"
        "#define COLO_ITEM_OBS_CODE_SCALE %d\n"
        "\n"
        "/* Slots the observation adds in; the table holds zero at both. */\n"
        "#define COLO_ITEM_OBS_OVERLAY_EQUIPPED %d\n"
        "#define COLO_ITEM_OBS_OVERLAY_HP_HEAL %d\n"
        "\n"
        "/* Rows live in osrs_colosseum_item_obs_table.inc so each consumer names its own\n"
        " * storage: src/ocean.cu wants a __device__ copy, the viewer wants a host one, and\n"
        " * a single guarded definition would hand whichever included first to both. */\n"
        "\n"
        "#endif\n",
        OSRS_INVENTORY_CELL_OBS_CODE_COUNT,
        OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT,
        GEN_BASE_PRAYER,
        GEN_BASE_LEVEL,
        OSRS_INVENTORY_CELL_OBS_CODE_SCALE,
        OSRS_INVENTORY_CELL_COMPACT_EQUIPPED,
        OSRS_INVENTORY_CELL_COMPACT_HP_HEAL);
    fclose(out);
}

static void write_table(const char* path) {
    FILE* out = open_or_die(path);
    fprintf(out,
        "/* Generated by ocean/osrs/tools/gen_colosseum_item_obs_table.c. Do not edit.\n"
        " * Included as the initialiser body of a [ROWS][COLS] float array. */\n");

    for (int code = 0; code < OSRS_INVENTORY_CELL_OBS_CODE_COUNT; code++) {
        require_code_round_trip(code);
        require_hitpoints_free(code);

        float row[OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT];
        build_row(row, code, GEN_PROBE_HITPOINTS_A);

        fprintf(out, "{");
        for (int f = 0; f < OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT; f++) {
            if (f) fprintf(out, ", ");
            emit_float(out, row[f]);
        }
        fprintf(out, "},\n");
    }
    fclose(out);
}

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: %s <header.h> <table.inc>\n", argv[0]);
        return 1;
    }
    if (OSRS_INVENTORY_CELL_OBS_CODE_COUNT > OSRS_INVENTORY_CELL_OBS_CODE_SCALE) {
        fprintf(stderr,
            "colosseum item obs table: %d codes exceeds the scale %d; the code/scale round "
            "trip is only exact in bf16 while a code fits in the scale's significand\n",
            OSRS_INVENTORY_CELL_OBS_CODE_COUNT, OSRS_INVENTORY_CELL_OBS_CODE_SCALE);
        return 1;
    }
    for (int code = 0; code < OSRS_INVENTORY_CELL_OBS_CODE_COUNT; code++) {
        int back = osrs_inventory_cell_obs_code_decode(
            osrs_inventory_cell_obs_code_encode(code));
        if (back == code) continue;
        fprintf(stderr, "colosseum item obs table: code %d encodes back as %d\n", code, back);
        return 1;
    }
    write_header(argv[1]);
    write_table(argv[2]);
    return 0;
}
