/* Emits the shared OSRS item observation table consumed by entity encoders.
 *
 *   cc -std=c11 -O2 -I. -o /tmp/gen_osrs_item_obs \
 *      ocean/osrs/tools/gen_osrs_item_obs_table.c -lm
 *   /tmp/gen_osrs_item_obs ocean/osrs/osrs_item_obs_generated.h \
 *                           ocean/osrs/osrs_item_obs_table.inc
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ocean/osrs/osrs_inventory_clicks.h"

#define GEN_BASE_HITPOINTS 99
#define GEN_BASE_PRAYER 99
#define GEN_BASE_RANGED 99

static void emit_float(FILE* out, float v) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%.9g", (double)v);
    if (!strpbrk(buf, ".eEnN")) strncat(buf, ".0", sizeof(buf) - strlen(buf) - 1);
    fprintf(out, "%sf", buf);
}

static void build_row(float* row, int code) {
    osrs_write_inventory_cell_obs_table_row(
        row, code, GEN_BASE_HITPOINTS, GEN_BASE_PRAYER, GEN_BASE_RANGED);
}

static void require_code_round_trip(int code) {
    OsrsInventoryCell cell = osrs_inventory_cell_for_obs_code(code);
    int back = osrs_inventory_cell_obs_code(cell.item_idx, cell.raw_osrs_id);
    if (back == code) return;
    fprintf(stderr,
        "OSRS item obs table: code %d resolves to item %u raw %u, which codes back as "
        "%d. Two codes share one cell content and the table is not a function of the code.\n",
        code, cell.item_idx, cell.raw_osrs_id, back);
    exit(1);
}


static FILE* open_or_die(const char* path) {
    FILE* f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "OSRS item obs table: cannot write %s\n", path);
        exit(1);
    }
    return f;
}

static void write_header(const char* path) {
    FILE* out = open_or_die(path);
    fprintf(out,
        "/* Generated by ocean/osrs/tools/gen_osrs_item_obs_table.c. Do not edit.\n"
        " * Dependency-free on purpose: src/ocean.cu includes it and no OSRS header. */\n"
        "#ifndef OSRS_ITEM_OBS_GENERATED_H\n"
        "#define OSRS_ITEM_OBS_GENERATED_H\n"
        "\n"
        "#define OSRS_ITEM_OBS_TABLE_ROWS %d\n"
        "#define OSRS_ITEM_OBS_TABLE_COLS %d\n"
        "#define OSRS_ITEM_OBS_TABLE_BASE_HITPOINTS %d\n"
        "#define OSRS_ITEM_OBS_TABLE_BASE_PRAYER %d\n"
        "#define OSRS_ITEM_OBS_TABLE_BASE_RANGED %d\n"
        "\n"
        "#define OSRS_ITEM_OBS_CODE_SCALE %d\n"
        "\n"
        "#define OSRS_ITEM_OBS_OVERLAY_EQUIPPED %d\n"
        "#define OSRS_ITEM_OBS_OVERLAY_HP_HEAL %d\n"
        "\n"
        "#endif\n",
        OSRS_INVENTORY_CELL_OBS_CODE_COUNT,
        OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT,
        GEN_BASE_HITPOINTS,
        GEN_BASE_PRAYER,
        GEN_BASE_RANGED,
        OSRS_INVENTORY_CELL_OBS_CODE_SCALE,
        OSRS_INVENTORY_CELL_COMPACT_EQUIPPED,
        OSRS_INVENTORY_CELL_COMPACT_HP_HEAL);
    fclose(out);
}

static void write_table(const char* path) {
    FILE* out = open_or_die(path);
    fprintf(out,
        "/* Generated by ocean/osrs/tools/gen_osrs_item_obs_table.c. Do not edit.\n"
        " * Included as the initialiser body of a [ROWS][COLS] float array. */\n");

    for (int code = 0; code < OSRS_INVENTORY_CELL_OBS_CODE_COUNT; code++) {
        require_code_round_trip(code);

        float row[OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT];
        build_row(row, code);

        fprintf(out, "{");
        for (int f = 0; f < OSRS_INVENTORY_CELL_OBS_FEATURES_COMPACT; f++) {
            if (f) fprintf(out, ", ");
            emit_float(out, row[f]);
        }
        fprintf(out, "},\n");
    }
    fclose(out);
}

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: %s <header.h> <table.inc>\n", argv[0]);
        return 1;
    }
    if (OSRS_INVENTORY_CELL_OBS_CODE_COUNT > OSRS_INVENTORY_CELL_OBS_CODE_SCALE) {
        fprintf(stderr,
            "OSRS item obs table: %d codes exceeds the scale %d; the code/scale round "
            "trip is only exact in bf16 while a code fits in the scale's significand\n",
            OSRS_INVENTORY_CELL_OBS_CODE_COUNT, OSRS_INVENTORY_CELL_OBS_CODE_SCALE);
        return 1;
    }
    for (int code = 0; code < OSRS_INVENTORY_CELL_OBS_CODE_COUNT; code++) {
        int back = osrs_inventory_cell_obs_code_decode(
            osrs_inventory_cell_obs_code_encode(code));
        if (back == code) continue;
        fprintf(stderr, "OSRS item obs table: code %d encodes back as %d\n", code, back);
        return 1;
    }
    write_header(argv[1]);
    write_table(argv[2]);
    return 0;
}
