[base]
package = ocean
env_name = puffer_slimevolley
policy_name = Policy
rnn_name = Recurrent
[vec]
backend= Multiprocessing


[env]
num_agents=1
num_envs=4096
; 0 for single-agent (vs bot), 1 for two-agent (self-play), 2 for eval agent vs bot (trained via selfplay)
selfplay = 1
[train]
total_timesteps = 400_000_000
minibatch_size = 32768
learning_rate = 0.0005
data_dir = experiments/sweep

[sweep.train.total_timesteps]
distribution = uniform
min = 100_000_000
max = 300_000_000
scale = 0.5


