/* Generated by ocean/osrs/tools/gen_osrs_item_obs_table.c. Do not edit.
 * Dependency-free on purpose: src/ocean.cu includes it and no OSRS header. */
#ifndef OSRS_ITEM_OBS_GENERATED_H
#define OSRS_ITEM_OBS_GENERATED_H

#define OSRS_ITEM_OBS_TABLE_ROWS 201
#define OSRS_ITEM_OBS_TABLE_COLS 15
#define OSRS_ITEM_OBS_TABLE_BASE_HITPOINTS 99
#define OSRS_ITEM_OBS_TABLE_BASE_PRAYER 99
#define OSRS_ITEM_OBS_TABLE_BASE_RANGED 99

#define OSRS_ITEM_OBS_CODE_SCALE 256

#define OSRS_ITEM_OBS_OVERLAY_EQUIPPED 1
#define OSRS_ITEM_OBS_OVERLAY_HP_HEAL 10

#endif
