/* Generated by ocean/osrs/scripts/osrs_asset_manifest.py. */
#ifndef OSRS_ASSETS_GENERATED_H
#define OSRS_ASSETS_GENERATED_H

#include <stddef.h>

typedef enum {
    OSRS_ASSET_GROUP_CORE = 0,
    OSRS_ASSET_GROUP_INFERNO = 1,
    OSRS_ASSET_GROUP_ZULRAH = 2,
    OSRS_ASSET_GROUP_COLOSSEUM = 3,
    OSRS_ASSET_GROUP_GUI = 4,
    OSRS_ASSET_GROUP_ITEMS = 5,
    OSRS_ASSET_GROUP_HEADERS = 6,
    OSRS_ASSET_GROUP_COMBAT_VISUALS = 7,
    OSRS_ASSET_GROUP_WILDERNESS = 8,
    OSRS_ASSET_GROUP_PVP = 9,
    OSRS_ASSET_GROUP_COUNT,
} OsrsAssetGroupKind;

typedef struct {
    const char* name;
    const char* const* paths;
    size_t path_count;
} OsrsAssetGroup;

static const char* const OSRS_ASSET_CORE_PATHS[] = {
    "equipment.models",
    "equipment.anims",
    "equipment.atlas",
    "equipment.tanim",
    "projectiles.models",
    "projectiles.atlas",
    "projectiles.anims",
    "spotanims.bin",
    "fonts/runescape.ttf",
    "fonts/runescape_small.ttf",
    "ui/interfaces.bin",
    "ui/interface_manifest.json",
};

static const char* const OSRS_ASSET_INFERNO_PATHS[] = {
    "inferno.models",
    "inferno.anims",
    "inferno.terrain",
    "inferno.objects",
    "inferno.atlas",
    "inferno_zuk.objects",
    "inferno.cmap",
    "inferno_npcs.models",
    "inferno_npcs.anims",
    "inferno_npcs.atlas",
};

static const char* const OSRS_ASSET_ZULRAH_PATHS[] = {
    "zulrah.models",
    "zulrah.anims",
    "zulrah.terrain",
    "zulrah.objects",
    "zulrah.atlas",
    "zulrah.cmap",
};

static const char* const OSRS_ASSET_COLOSSEUM_PATHS[] = {
    "colosseum.terrain",
    "colosseum.objects",
    "colosseum.atlas",
    "colosseum.cmap",
    "colosseum_npcs.models",
    "colosseum_npcs.anims",
    "colosseum_npcs.atlas",
    "sprites/colosseum/modifiers/5534.png",
    "sprites/colosseum/modifiers/5535.png",
    "sprites/colosseum/modifiers/5536.png",
    "sprites/colosseum/modifiers/5537.png",
    "sprites/colosseum/modifiers/5538.png",
    "sprites/colosseum/modifiers/5539.png",
    "sprites/colosseum/modifiers/5540.png",
    "sprites/colosseum/modifiers/5541.png",
    "sprites/colosseum/modifiers/5542.png",
    "sprites/colosseum/modifiers/5543.png",
    "sprites/colosseum/modifiers/5544.png",
    "sprites/colosseum/modifiers/5545.png",
    "sprites/colosseum/modifiers/5546.png",
    "sprites/colosseum/modifiers/5547.png",
    "sprites/colosseum/modifiers/5549.png",
    "sprites/colosseum/modifiers/5550.png",
    "sprites/colosseum/modifiers/5551.png",
    "sprites/colosseum/modifiers/5552.png",
    "sprites/colosseum/modifiers/5553.png",
    "sprites/colosseum/modifiers/5554.png",
    "sprites/colosseum/modifiers/5556.png",
    "sprites/colosseum/modifiers/5558.png",
    "sprites/colosseum/modifiers/5559.png",
    "sprites/colosseum/modifiers/5562.png",
    "sprites/colosseum/modifiers/5564.png",
    "sprites/colosseum/modifiers/5565.png",
    "sprites/colosseum/modifiers/5566.png",
    "sprites/colosseum/modifiers/5567.png",
    "sprites/colosseum/modifiers/5568.png",
    "sprites/colosseum/modifiers/5569.png",
    "sprites/colosseum/modifiers/5571.png",
    "sprites/colosseum/modifiers/5573.png",
    "sprites/colosseum/modifiers/5574.png",
    "sprites/colosseum/modifiers/5577.png",
};

static const char* const OSRS_ASSET_GUI_PATHS[] = {
    "sprites/gui/compass.png",
    "sprites/gui/side_panel_bg.png",
    "sprites/gui/orb_frame.png",
    "sprites/gui/headicons_prayer_0.png",
    "sprites/gui/hitmarks_0.png",
    "sprites/gui/cross_yellow_1.png",
    "sprites/gui/side_icon_inventory.png",
    "sprites/gui/tradebacking_dark.png",
    "sprites/gui/osrs_stretch_side_topbottom_0.png",
    "sprites/gui/wornicons_11.png",
    "sprites/gui/skill_icon_23.png",
    "sprites/gui/prayeron_24.png",
    "sprites/gui/magicon_47.png",
    "sprites/gui/standard_spell_on_79.png",
    "sprites/gui/minimap_alpha_mask.png",
    "sprites/gui/prayerglow_0.png",
};

static const char* const OSRS_ASSET_ITEMS_PATHS[] = {
    "sprites/items/30070.png",
    "sprites/items/28945.png",
    "sprites/items/27641.png",
    "sprites/items/item_stack_variants.tsv",
};

static const char* const OSRS_ASSET_HEADERS_PATHS[] = {
    "item_models.h",
    "player_models.h",
    "npc_models.h",
    "npc_models_inferno.h",
    "npc_models_zulrah.h",
    "npc_models_colosseum.h",
};

static const char* const OSRS_ASSET_COMBAT_VISUALS_PATHS[] = {
    "projectiles.models",
    "projectiles.atlas",
    "projectiles.anims",
    "spotanims.bin",
    "equipment.anims",
    "inferno.anims",
    "zulrah.anims",
};

static const char* const OSRS_ASSET_WILDERNESS_PATHS[] = {
    "wilderness.cmap",
    "wilderness.terrain",
    "wilderness.objects",
    "wilderness.atlas",
};

static const char* const OSRS_ASSET_PVP_PATHS[] = {
    "equipment.models",
    "equipment.anims",
    "equipment.atlas",
    "equipment.tanim",
    "projectiles.models",
    "projectiles.atlas",
    "projectiles.anims",
    "spotanims.bin",
    "ui/interfaces.bin",
    "ui/interface_manifest.json",
    "wilderness.cmap",
    "wilderness.terrain",
    "wilderness.objects",
    "wilderness.atlas",
};

static const OsrsAssetGroup OSRS_ASSET_GROUPS[OSRS_ASSET_GROUP_COUNT] = {
    [OSRS_ASSET_GROUP_CORE] = {
        .name = "core",
        .paths = OSRS_ASSET_CORE_PATHS,
        .path_count = sizeof(OSRS_ASSET_CORE_PATHS) / sizeof(OSRS_ASSET_CORE_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_INFERNO] = {
        .name = "inferno",
        .paths = OSRS_ASSET_INFERNO_PATHS,
        .path_count = sizeof(OSRS_ASSET_INFERNO_PATHS) / sizeof(OSRS_ASSET_INFERNO_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_ZULRAH] = {
        .name = "zulrah",
        .paths = OSRS_ASSET_ZULRAH_PATHS,
        .path_count = sizeof(OSRS_ASSET_ZULRAH_PATHS) / sizeof(OSRS_ASSET_ZULRAH_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_COLOSSEUM] = {
        .name = "colosseum",
        .paths = OSRS_ASSET_COLOSSEUM_PATHS,
        .path_count = sizeof(OSRS_ASSET_COLOSSEUM_PATHS) / sizeof(OSRS_ASSET_COLOSSEUM_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_GUI] = {
        .name = "gui",
        .paths = OSRS_ASSET_GUI_PATHS,
        .path_count = sizeof(OSRS_ASSET_GUI_PATHS) / sizeof(OSRS_ASSET_GUI_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_ITEMS] = {
        .name = "items",
        .paths = OSRS_ASSET_ITEMS_PATHS,
        .path_count = sizeof(OSRS_ASSET_ITEMS_PATHS) / sizeof(OSRS_ASSET_ITEMS_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_HEADERS] = {
        .name = "headers",
        .paths = OSRS_ASSET_HEADERS_PATHS,
        .path_count = sizeof(OSRS_ASSET_HEADERS_PATHS) / sizeof(OSRS_ASSET_HEADERS_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_COMBAT_VISUALS] = {
        .name = "combat_visuals",
        .paths = OSRS_ASSET_COMBAT_VISUALS_PATHS,
        .path_count = sizeof(OSRS_ASSET_COMBAT_VISUALS_PATHS) / sizeof(OSRS_ASSET_COMBAT_VISUALS_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_WILDERNESS] = {
        .name = "wilderness",
        .paths = OSRS_ASSET_WILDERNESS_PATHS,
        .path_count = sizeof(OSRS_ASSET_WILDERNESS_PATHS) / sizeof(OSRS_ASSET_WILDERNESS_PATHS[0]),
    },
    [OSRS_ASSET_GROUP_PVP] = {
        .name = "pvp",
        .paths = OSRS_ASSET_PVP_PATHS,
        .path_count = sizeof(OSRS_ASSET_PVP_PATHS) / sizeof(OSRS_ASSET_PVP_PATHS[0]),
    },
};

#endif
