#ifndef OSRS_GFX_IDS_H
#define OSRS_GFX_IDS_H

#define GFX_RUNE_ARROW_LAUNCH 24
#define GFX_SPLASH          85
#define GFX_TRIDENT_CAST    665
#define GFX_TRIDENT_PROJ    1040
#define GFX_TRIDENT_IMPACT  1042
#define GFX_TUMEKENS_SHADOW_CAST   2125
#define GFX_TUMEKENS_SHADOW_PROJ   2126
#define GFX_TUMEKENS_SHADOW_IMPACT 2127
#define GFX_BLOWPIPE_SPEC   1043
#define GFX_DRAGON_ARROW_LAUNCH 1116
#define GFX_DRAGON_DART     1122

#endif
