/* Generated by ocean/osrs/tools/gen_colosseum_item_obs_table.c. Do not edit.
 * Dependency-free on purpose: src/ocean.cu includes it and no OSRS header. */
#ifndef OSRS_COLOSSEUM_ITEM_OBS_GENERATED_H
#define OSRS_COLOSSEUM_ITEM_OBS_GENERATED_H

#define COLO_ITEM_OBS_TABLE_ROWS 201
#define COLO_ITEM_OBS_TABLE_COLS 15
#define COLO_ITEM_OBS_TABLE_BASE_PRAYER 99
#define COLO_ITEM_OBS_TABLE_BASE_LEVEL 99

/* The observation carries code/SCALE; multiply back to index a row. A power of two
 * keeps the round trip exact in bf16 and keeps the code out of the global linear
 * layer's dynamic range. */
#define COLO_ITEM_OBS_CODE_SCALE 256

/* Slots the observation adds in; the table holds zero at both. */
#define COLO_ITEM_OBS_OVERLAY_EQUIPPED 1
#define COLO_ITEM_OBS_OVERLAY_HP_HEAL 10

/* Rows live in osrs_colosseum_item_obs_table.inc so each consumer names its own
 * storage: src/ocean.cu wants a __device__ copy, the viewer wants a host one, and
 * a single guarded definition would hand whichever included first to both. */

#endif
