'use strict';
const assert=require('node:assert/strict'),test=require('node:test'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const baseline=path.join(__dirname,'live_transfer_run_pairing_baseline_r1.cjs');
const candidate=path.join(__dirname,'live_transfer_run_pairing_r1.cjs');
const fixture=()=>({scene:'Arena',observed_utc:'2026-09-24T06:57:20.8303074+00:00',foreground:{isolated_session_verified:true},control:{lease_held:false,g1_policy_stream_running:false},private_ai:{proven:true,policy_proven:true,policy_active_gameplay_proven:false,policy_active_gameplay_reason:'exact_g1_pairing_not_proven',network_client_only:true,context_is_solo:true,solo_route_proven:true,opponent_is_ai:true,opponent_slot_is_ai:true,human_in_opponent_slot:false,opponent_slot_client_known:true,opponent_slot_has_client:false,opponent_human_bit_set:false,client_ai_difficulty:0,sparring_bot_number:1,round_active:true,round_number:1,phase:'RoundActive',client_visual_only_fighter_pair:true,local_slot:0,opponent_slot:1},measured_pairing:{reason:'mixed_supported_runtime_models_rejected',exact_g1_vs_g1:false,local_slot:0,opponent_slot:1,local_fighter:{semantic_robot_id:'g1',exact_g1_bone_signature:true,bone_count:30,runtime_bone_signature_sha256:'9d18e697233d9578b398fbe849cd59d65cb27a5c2223b2602db66a82a410e987'},opponent_fighter:{semantic_robot_id:'t800',exact_t800_bone_signature:true,bone_count:26,runtime_bone_signature_sha256:'ec0f8d0ae5bd170464f5393f9860959e47a54b8e73e4dc259a6fb955f46d3dab'}}});
for(const file of [baseline,candidate]){
 const d=require(file),name=file.includes('balance8')?'balance8':'baseline';
 test(name+': measured G1/T800 fails with explicit evidence',()=>{const s=fixture();assert.equal(d.provenG1T800Pairing(s).code,'unsupported_pairing:local_g1_opponent_t800');assert.throws(()=>d.rejectUnsupportedActivePairing(s),e=>e.unsupported_pairing?.opponent_robot_id==='t800');});
 test(name+': every scope/signature prerequisite remains required',()=>{const mutations=[s=>s.scene='Lobby',s=>s.foreground.isolated_session_verified=false,s=>s.private_ai.human_in_opponent_slot=true,s=>s.private_ai.policy_proven=false,s=>s.private_ai.proven=false,s=>s.private_ai.solo_route_proven=false,s=>s.private_ai.opponent_slot_has_client=true,s=>s.private_ai.round_active=false,s=>s.private_ai.client_visual_only_fighter_pair=false,s=>s.private_ai.sparring_bot_number=2,s=>s.measured_pairing.opponent_slot=0,s=>s.measured_pairing.local_fighter.bone_count=26,s=>s.measured_pairing.opponent_fighter.runtime_bone_signature_sha256='wrong',s=>s.measured_pairing.opponent_fighter.exact_t800_bone_signature=false];for(const mutate of mutations){const s=fixture();mutate(s);assert.equal(d.provenG1T800Pairing(s),null);}});
 test(name+': ready request followed by mixed spawn rejects promptly',async()=>{const s=fixture(),idle=fixture();Object.assign(idle.private_ai,{phase:'Idle',round_active:false,round_inactive:true,client_visual_only_fighter_pair:false});let commands=[],polls=0;await assert.rejects(d.ensurePrivateArena(idle,{enterPrivate:true,command:async c=>commands.push(c),getState:async()=>{polls++;return s;},wait:async()=>{},now:()=>0}),/unsupported_pairing:local_g1_opponent_t800/);assert.deepEqual(commands,['ReadyPrivateAiSession']);assert.equal(polls,1);});
 test(name+': successful G1 ready path unchanged',async()=>{const s=fixture(),idle=fixture();Object.assign(idle.private_ai,{phase:'Idle',round_active:false,round_inactive:true,client_visual_only_fighter_pair:false});Object.assign(s.private_ai,{policy_active_gameplay_proven:true});s.measured_pairing.exact_g1_vs_g1=true;s.measured_pairing.reason='exact_g1_vs_g1_runtime_pairing_proven_semantic_ids_recorded_not_trusted';s.measured_pairing.opponent_fighter={...s.measured_pairing.local_fighter};const commands=[];assert.equal(await d.ensurePrivateArena(idle,{enterPrivate:true,command:async c=>commands.push(c),getState:async()=>s,wait:async()=>{},now:()=>0}),s);assert.deepEqual(commands,['ReadyPrivateAiSession']);});
}
test('controller recovery rejects owned/unsafe scope and retains relaunch budget',async()=>{
 const code=fs.readFileSync(path.join(__dirname,'campaign_pairing_r1.cjs'),'utf8');
 const marker="if(process.argv[2]==='--verdict')";assert.equal(code.split(marker).length,2);
 const logs=[],calls=[];const fakeFs={existsSync:()=>false,createWriteStream:()=>({write:s=>logs.push(JSON.parse(s)),end(){}})};
 const context=vm.createContext({console,setTimeout,clearTimeout,setInterval,clearInterval,process:{env:{AB_DRIVER:baseline,AB_STAGE:'/stage',AB_MAX_RELAUNCHES:'3'}},require:n=>n==='node:fs'?fakeFs:n==='node:child_process'?{spawn(){throw Error('unexpected process launch');}}:require(n),calls});
 vm.runInContext(code.split(marker)[0]+"\nglobalThis.recover=recycleUnsupportedPairing;run=async(cmd,args)=>{calls.push([cmd,args]);return {code:0};};",context);
 const raw=fixture(),proof=require(baseline).provenG1T800Pairing(raw),s={scene:'Arena',isolated_session_verified:true,lease_held:false,g1_policy_stream_running:false,private_ai:raw.private_ai,unsupported_pairing:proof};
 for(const k of ['lease_held','g1_policy_stream_running'])await assert.rejects(context.recover({...s,[k]:true},{label:'same',policy_rng_seed:803}),/scope not verified/);
 await context.recover(s,{label:'same',policy_rng_seed:803});assert.equal(calls.length,1);assert.equal(calls[0][1][0],path.join('/stage','root-campaign','recycle_owned_client.sh'));assert.equal(logs[0].policy_rng_seed,803);assert.equal(logs[0].retry_same_seed,true);assert.equal(logs[0].counted,false);
 vm.runInContext('relaunches=3;',context);await assert.rejects(context.recover(s,{label:'same',policy_rng_seed:803}),/relaunch budget exhausted/);assert.equal(calls.length,1);
});
test('candidate schema and checkpoint checks retained',()=>{const d=require(candidate),schema='rek.native5.scaled_polar_xy.balance8_v1',sha='a'.repeat(64),mask='b'.repeat(64),ready={type:'ready',checkpoint_sha256:sha,feature_mask_sha256:mask,native_cuda:true,environment_stepping:false,observation_schema:schema,precision:'bf16',selection:'sampled',observations:223,actions:33,hidden_size:256,num_layers:2};d.validateWorkerReady(ready,sha,mask,schema);assert.throws(()=>d.validateWorkerReady({...ready,observation_schema:'rek.native5.scaled_polar_xy.v1'},sha,mask,schema));assert.throws(()=>d.validateWorkerReady(ready,'c'.repeat(64),mask,schema));});
